### ISSUE TITLE
Manual DAAC query and retrieval script

### ISSUE THREAD

**Issue by hhlee445** [nasa/opera-sds-pcm#1]
SDS needs to be able to query various DAACs (ASF DAAC, LP DAAC, or PO DAAC) and retrieve data from them to OPERA ISL location

Following information should be passed to query.
- product type(s)
- which DAAC (ASF DAAC or LP DAAC)
- time range (start date and/or end date)
- ISL bucket name to download
- access info to DAACs (optional)
- download mode (S3-default or http)

Note: we can use NISAR daac retrieval script as reference.
https://github.jpl.nasa.gov/IEMS-SDS/nisar-pcm/blob/develop/tools/sds_daac_retrieval.py

This script will be used by a PCM worker to automatically query and retrieve data into OPERA ISL S3 bucket.

**Comment by maseca** [comment]
Requirements satisfied by existing script: https://github.com/podaac/data-subscriber

**Comment by hhlee445** [comment]
Can you rename the script to general name and commit to our github repo?

**Comment by maseca** [comment]
It makes more sense to me to leave the code in its own open source repo. The code is still being extended and maintained by the original team; if we were to copy and paste the code into our repo we would no longer receive updates to the code.

**Comment by hhlee445** [comment]
Can you document the instruction to execute the command?

**Comment by hhlee445** [comment]
It throws an error at the end of execution.

```
Traceback (most recent call last):
  File "daac_data_subscriber.py", line 685, in <module>
    run()
  File "daac_data_subscriber.py", line 610, in run
    with open(data_path + "/.update", "w") as f:
  File "/export/home/hysdsops/mozart/lib/python3.8/site-packages/smart_open/smart_open_lib.py", line 188, in open
    fobj = _shortcut_open(
  File "/export/home/hysdsops/mozart/lib/python3.8/site-packages/smart_open/smart_open_lib.py", line 361, in _shortcut_open
    return _builtin_open(local_path, mode, buffering=buffering, **open_kwargs)
FileNotFoundError: [Errno 2] No such file or directory: 'opera-dev-isl-fwd-hyunlee/.update'
```

**Comment by maseca** [comment]
Yes, I will write a wiki page on usage. It looks like the changes were not properly merged. I will make a new PR.

**Comment by maseca** [comment]
https://wiki.jpl.nasa.gov/display/operasds/DAAC+Query+Script+Usage

I will add more feature usage descriptions as they come up in implementation.
