### ISSUE TITLE
[Bug]: SoftTimeLimitExceeded exception with query timer

### ISSUE THREAD

**Issue by hhlee445** [nasa/opera-sds-pcm#116]
### Checked for duplicates

Yes - I've already checked

### Describe the bug

When I tested the PCM ER4 release on I&T venue, I noticed that data-subscriber-query-timer was throwing an exception as 
<img width="1144" alt="Screen Shot 2022-05-26 at 7 13 30 PM" src="https://user-images.githubusercontent.com/47543396/171453560-662da8b0-1ea1-49da-9d6d-3ef4a0b7f875.png">
)

### What did you expect?

I expected the timer completed the query task without any error.

### Reproducible steps

```bash
1. Enable query timer if the timer is in disabled state.
2. Wait until the timer gets triggers and executed.
```

### Environment

```bash
- OPERA PCM ER4.0
```

**Comment by maseca** [comment]
I believe this was resolved by using the public Verdi AMIs instead of private, is that correct?

**Comment by hhlee445** [comment]
@philipjyoon Did you see SoftTimeLimitExceeded exception on newly deployed I&T venue?

**Comment by philipjyoon** [comment]
@hhlee445 I&T no longer has this issue. As @maseca mentioned, this issue was resolved by changing the Verdi security group to use the non-private one.
