### ISSUE TITLE
Document CMR Query in cURL form

### ISSUE THREAD

**Issue by maseca** [nasa/opera-sds-pcm#119]

**Comment by maseca** [comment]
```
curl [-H "CMR-Search-After: <search_after_id>"] \
"https://cmr.earthdata.nasa.gov/search/granules.umm_json\
?scroll=false\
&page_size=2000\
&sort_key=-start_date\
&provider=LPCLOUD\
&ShortName=<HLSL30 or HLSS30>\
&updated_since=<YYYY-MM-DDThh%3Amm%3AssZ>\
&token=<...>\
&bounding_box=-180,-90,180,90"
```

**Comment by maseca** [comment]
Does this suffice? @LucaCinquini

**Comment by maseca** [comment]
# L30
curl [-H "CMR-Search-After: <search_after_id>"] \
"https://cmr.earthdata.nasa.gov/search/granules.umm_json\
?scroll=false\
&page_size=2000\
&sort_key=-start_date\
&provider=LPCLOUD\
&ShortName=HLSL30\
&updated_since=2022-03-2701%3A00%3A00Z\
&token=<...>\
&bounding_box=-180,-90,180,90\
&temporal=2022-03-2701%3A00%3A00Z,2022-03-2702%3A00%3A00Z"

Total Objects: 1071
Total Size: 12.4 GiB
Duration: 10 minutes

# S30
curl [-H "CMR-Search-After: <search_after_id>"] \
"https://cmr.earthdata.nasa.gov/search/granules.umm_json\
?scroll=false\
&page_size=2000\
&sort_key=-start_date\
&provider=LPCLOUD\
&ShortName=HLSS30\
&updated_since=2022-03-2701%3A00%3A00Z\
&token=<...>\
&bounding_box=-180,-90,180,90\
&temporal=2022-03-2701%3A00%3A00Z,2022-03-2702%3A00%3A00Z"

Total Objects: 1645
Total Size: 22.7 GiB
Duration: 18 minutes

# Note
Metrics reflect consecutive calls via the "CMR-Search-After" header, which functions similarly to paging. Initial request does not use the header, as it is provided by the response.

**Comment by LucaCinquini** [comment]
Thanks Max - great job.
