### ISSUE TITLE
[Bug]: Auto-scaling behaving unexpectedly when ASG "JobsPerInstance" metric utilized

### ISSUE THREAD

**Issue by riverma** [nasa/opera-sds-pcm#144]
### Checked for duplicates

Yes - I've already checked

### Describe the bug

Paraphrased from a conversation with @philipjyoon:

We'd like to use the ASG auto-scaling policy of JobsPerInstance instead of JobsWaitingPerInstance to better scale up EC2s for long-running jobs such as the PGE jobs as recommended by @pymonger. 

We used that setting for the first time in our latest load test and seeing that it basically renders ASG moot altogether. All our ASG were stuck at 1-2 instances while our queues piled up to tens of thousands. (Desired was set to 1-2 and the actual number of instances were the same. We saw no cases where actual instance count was short of desired.) 

We confirmed in AWS console that the setting took effect and the rest of the Terraform scripts and state files seem correct. (We may have to do deep dive validation tho.) One thing that seems off to us is that the metric collected in cloudwatch for that AWS mentions JobsWaitingPerInstance as opposed to JobsPerInstance. So there may be some inconsistencies in setup of the cluster.

### What did you expect?

We expect our HLS PGE (or other queues) to scale to the fullest extent possible, based on number of jobs available in the queue - not be stuck at a single instance.

### Reproducible steps

```bash
1. Set `total_job_metric = true` within `variables.tf`, e.g. https://github.com/nasa/opera-sds-pcm/blob/develop/cluster_provisioning/dev-common/variables.tf#L459
2. Shutdown, start up cluster
3. Initiate jobs and observe ASG's to hover near zero
```

### Environment

```bash
- HySDS v4
- Mozart
- AWS
```

**Comment by riverma** [comment]
Per conversations with @mcayanan - the following observation was made for changes required to `supervisord.conf.mozart` (i.e. [here](https://github.com/nasa/opera-sds-pcm/blob/develop/conf/sds/files/supervisord.conf.mozart#L235-L238))

```
# target tracking metrics
 {% for q in QUEUES %}
 {% set queue = q['QUEUE_NAME'] | trim -%}
 {% set use_job_total = q.get('TOTAL_JOBS_METRIC', False) -%}
 [program:sync_ec2_target_tracking_metric-{{ queue }}]
 directory={{ OPS_HOME }}/mozart/ops/hysds/scripts
 command={{ OPS_HOME }}/mozart/ops/hysds/scripts/sync_ec2_target_tracking_metric.py --interval 60 -u {{ MOZART_RABBIT_USER }} -p {{ MOZART_RABBIT_PASSWORD }} {% if use_job_total == True %}--total_jobs {% endif %}{{ queue }} {{ VENUE }}-{{ queue }}
 process_name=%(program_name)s
 priority=1
 numprocs=1
```

**Comment by hhlee445** [comment]
- Modified supervisord.conf.mozart  
- Modified variables.tf to define total_job_metrics for queues
- Commited https://github.com/nasa/opera-sds-pcm/commit/7236ff3f14205fe4ee7237e8c3a2c36adbfb47bf

**Comment by philipjyoon** [comment]
I think we're still missing something. I looked at the cloudwatch metric for these ASGs for the light 1x test performed last week, the metrics were still named Jobs**Waiting**PerInstance... This explains why the behavior we observed was pretty much the same as we had seen before.

Item 10 here for screenshot
https://wiki.jpl.nasa.gov/display/operasds/Lite+Load+Test+with+total_jobs_metric+%3D+true%2C+1X+7-13-2022

**Comment by riverma** [comment]
We've observed this metric working well for our recent load tests, per a recent patch. Closing.
