### ISSUE TITLE
[New Feature]: Streaming logs to a singular place (ELK Stack vs CloudWatch)

### ISSUE THREAD

**Issue by hhlee445** [nasa/opera-sds-pcm#159]
### Checked for duplicates

Yes - I've already checked

### Alternatives considered

No - I haven't considered

### Describe the feature request

We want to capture system level logs to a singular place so that operator can easily troubleshoot system oddities that may not be apparent at the User Interface. 

The trade study was done by other projects and documented in https://wiki.jpl.nasa.gov/pages/viewpage.action?spaceKey=NISARSDS&title=Streaming+Logs+to+ELK+Stack+vs+CloudWatch

We can get an idea how we can achieve our logging mechanism by NISAR's implementation:
https://github.jpl.nasa.gov/IEMS-SDS/nisar-pcm/compare/NSDS-1829

**Comment by riverma** [comment]
Suggested logs to monitor by Lela Rodriguez:

- RabbitMQ logs
- mozart/log dir:
mozart_job_management.log
orchestrator_datasets-00.log
orchestrator_jobs-00.log
process_events.log
process_events_tasks-00.log
supervisord.log
sync_ec2_target_tracking_metric-swot-job_worker-*.log
watchdog_job_timeouts.log
watchdog_task_timeouts.log
watchdog_worker_timeouts.log
instance_stats.log
logstash_indexer.log
 
AWS / other HySDS 
- spot terminations

**Comment by riverma** [comment]
@hhlee445 - great to hear!

Couple questions:
- What's the best place to understand the log files we're _expecting_ to collect? 
- Have we done testing to collect our cost per day of running nominal logging scenarios?
