### ISSUE TITLE
[Bug]: Jobs in queue state for many days and never started

### ISSUE THREAD

**Issue by hhlee445** [nasa/opera-sds-pcm#178]
### Checked for duplicates

Yes - I've already checked

### Describe the bug

When SDS performed load test, we noticed that there are 5 jobs that were queued as early as on 7-27 and never started. They are various: cnm notify, sciflo, and state-config. What's interesting is that we observed a similar thing on the INT cluster too.

NISAR team suggested that we can investigate the issue by analyzing the watchdog log with payload id after login into the mozart.

1. tags: trigger-send_cnm_notify_msg_L3_DSWX_HLS
status: job-queued
resource: job
index: job_status-current
ID: 9fde536f-137a-4d55-a368-10e723bc5b94
payload_id: 9fde536f-137a-4d55-a368-10e723bc5b94
timestamp: 2022-07-31T18:11:12.870Z
job: send_notify_msg__1.0.0-rc.2.0-OPERA_L3_DSWx_HLS_S2B_30_T47UQP_20220128T042029Z_20220731T175916Z_v0.1_001-20220731T181112.870407Z
queue: opera-job_worker-send_cnm_notify
time queued: 2022-07-31T18:11:12.870421Z

2. tags: trigger-L3_DSWx_HLS_STATE_CONFIG
status: job-queued
resource: job
index: job_status-current
ID: a69893f9-743d-487f-9370-7ef49802b2d8
payload_id: a69893f9-743d-487f-9370-7ef49802b2d8
timestamp: 2022-07-30T21:58:54.060Z
job: L3_DSWx_HLS_STATE_CONFIG__1.0.0-rc.2.0-HLS.L30.T32NKK.2022027T095130.v2.0.B07-20220730T215854.60795Z
queue: opera-job_worker-l3_dswx_hls_state_config
time queued: 2022-07-30T21:58:54.060808Z

3. tags: trigger-SCIFLO_L3_DSWx_HLS_S30
status: job-queued
resource: job
index: job_status-current
ID: 5fa4d9e3-4962-4b9c-b037-295b9146b7a1
payload_id: 5fa4d9e3-4962-4b9c-b037-295b9146b7a1
timestamp: 2022-07-29T22:21:35.225Z
job: SCIFLO_L3_DSWx_HLS__1.0.0-rc.2.0-HLS.S30.T34MFV.2022026T084129.v2.0_state_config-20220729T222135.225501Z
queue: opera-job_worker-sciflo-l3_dswx_hls
time queued: 2022-07-29T22:21:35.225509Z

4. tags: trigger-send_cnm_notify_msg_L3_DSWX_HLS
status: job-queued
resource: job
index: job_status-current
ID: a9ca61ec-8845-4f13-aa86-fe192e934386
payload_id: a9ca61ec-8845-4f13-aa86-fe192e934386
timestamp: 2022-07-28T18:25:29.720Z
job: send_notify_msg__1.0.0-rc.2.0-OPERA_L3_DSWx_HLS_S2B_30_T47TPM_20220125T041039Z_20220728T180217Z_v0.1_001-20220728T182529.720203Z
queue: opera-job_worker-send_cnm_notify
time queued: 2022-07-28T18:25:29.720214Z

5. tags: trigger-SCIFLO_L3_DSWx_HLS_S30
status: job-queued
resource: job
index: job_status-current
ID: f5287bb0-e48e-4bb2-bad9-6aaae3066b32
payload_id: f5287bb0-e48e-4bb2-bad9-6aaae3066b32
timestamp: 2022-07-27T21:19:28.095Z
job: SCIFLO_L3_DSWx_HLS__1.0.0-rc.2.0-HLS.S30.T36PZR.2022024T080119.v2.0_state_config-20220727T211928.95387Z
queue: opera-job_worker-sciflo-l3_dswx_hls
time queued: 2022-07-27T21:19:28.095396Z 

### What did you expect?

I expected all jobs were started and there was no queued jobs after all processing was done.

### Environment

```bash
- PCM 1.0.0-rc.2.0 
- dev-common cluster
```

**Comment by chrisjrd** [comment]
A similar issue was fixed in hysds-core as HC-393.

But we can establish a procedure to address this, since we use version with the fix. The procedure would be to scale down the autoscaling group to 0, so that the workers do not remain up.

**Comment by riverma** [comment]
How would setting the ASG ensure the queued jobs start? Not quite following @chrisjrd

**Comment by chrisjrd** [comment]
I don't know why it works. But this is the recommendation from Michael or Gerald. By bringing down the workers that stayed up without processing further tasks, the flow will pick up from that stagnant state.

**Comment by hhlee445** [comment]
Won't fix this issue. We consolidated the download/extract/ingest pipeline.
