### ISSUE TITLE
[Bug]: Some HLS products are in ISL bucket but never started INGEST_STAGED jobs

### ISSUE THREAD

**Issue by hhlee445** [nasa/opera-sds-pcm#179]
### Checked for duplicates

Yes - I've already checked

### Describe the bug

After the load test was completed, there are 35 HLS products are in the ISL bucket (**_s3://opera-dev-isl-fwd_**) and never started INGEST_STAGED jobs.

### What did you expect?

We expected all products in the ISL bucket were ingested successfully and continued to execute next jobs.

### Environment

```bash
- PCM 1.0.0-rc.2.0
- dev-common cluster
```

**Comment by chrisjrd** [comment]
we can establish a procedure to address this.

We have existing terraform tests that check for this "event misfire".

we can find the associated code here (https://github.jpl.nasa.gov/IEMS-SDS/nisar-pcm/tree/develop/cluster_provisioning/dev-e2e-event-misfire)
 and here (https://github.jpl.nasa.gov/IEMS-SDS/pcm-lambdas/blob/develop/lambdas/event-misfire/event-misfire.py)

We can also re-upload the S3 file in question.

**Comment by hhlee445** [comment]
Since we no longer staged the HLS products in ISL bucket, we won't fix it.
