### ISSUE TITLE
Benchmark testing for DAAC query/retrieval

### ISSUE THREAD

**Issue by hhlee445** [nasa/opera-sds-pcm#22]
PCM needs to test how fast we can query and retrieve the data from DAAC (specially from ASF DAAC) for preparation of bulk historical processing.

**Comment by maseca** [comment]
Benchmarking will be performed with LP DAAC data. See #65 for ASF DAAC data.

**Comment by maseca** [comment]
See:
https://wiki.jpl.nasa.gov/display/operasds/2022-04-11+Benchmark
