### ISSUE TITLE
[New Feature]: Add "survey" feature to daac_data_subscriber.py code

### ISSUE THREAD

**Issue by philipjyoon** [nasa/opera-sds-pcm#232]
### Checked for duplicates

Yes - I've already checked

### Alternatives considered

Yes - and alternatives don't suffice

### Related problems

Very often during testing (and maybe even ops) one wishes to know the number of granules a particular date range would yield when queries/downloaded. Since the daac_data_subscriber.py script contains all the code needed to query the CMR it's natural to just add one more feature to it where it reports the number of granules found but doesn't alter the PCM system (ElasticSearch) in any way.

### Describe the feature request

The script currently has "query" "download" and "full" running modes. Create another which is "survey" which would print out the number of granules found to the console and exit without altering ElasticSearch indices.

Alternatively do not create a new mode. Just add option called "--survey-only" to the query mode and implement the same logic.

**Comment by philipjyoon** [comment]
Better way might be to create a library/module out of the existing daac_data_subscriber.py and then create a new executable that performs survey.

**Comment by riverma** [comment]
@maseca FYI.
