### ISSUE TITLE
[Bug]: Download verdi workers aren't deleting enough files and that causes download jobs to fail

### ISSUE THREAD

**Issue by philipjyoon** [nasa/opera-sds-pcm#236]
### Checked for duplicates

Yes - I've already checked

### Describe the bug

The job spec for the download jobs has disk_usage parameter of 1GB. This is too low and because of this the verdi download workers weren't cleaning up the local EBS in the EC2. The data piled on until the disk got full and that's failed all the subsequent download jobs.

### What did you expect?

Expected all download jobs to run to completion without errors.

### Reproducible steps

```bash
1.
2.
3.
...
```

### Environment

```bash
- Version of this software [e.g. vX.Y.Z]
- Operating System: [e.g. MacOSX with Docker Desktop vX.Y]
...
```

**Comment by riverma** [comment]
@philipjyoon - not sure I fully understand the `disk_usage` parameter. Is the value reflective of the amount of disk space margin allowed until a clean-up is invoked? Or something else?

**Comment by philipjyoon** [comment]
This was fixed by the commit referenced.
