### ISSUE TITLE
[New Feature]: Create purge_aws_resources variable in terraform

### ISSUE THREAD

**Issue by philipjyoon** [nasa/opera-sds-pcm#237]
### Checked for duplicates

Yes - I've already checked

### Alternatives considered

Yes - and alternatives don't suffice

### Related problems

In the PST venue (and probably also OPS in the future) we don't want to delete any data from S3 buckets when we destroy the cluster. Currently in main.tf it always deletes all S3 data at destroy time by running purge_aws_resources.sh We should create a terraform variable, default to true, that controls whether destroy deletes the resources at destroy time.

### Describe the feature request

As written above

**Comment by philipjyoon** [comment]
5 buckets are currently being automatically deleted: code, dataset, triage, lts, and osl.

For sure we want to delete code (cc) and preserve dataset (rs). I don't know about triage, lts, and osl on whether we would also want to preserve those when preserving dataset

**Comment by hhlee445** [comment]
We don't use **lts** and **osl** buckets so we don't need to preserve those.  We should preserve **triage** bucket for failed jobs.

**Comment by philipjyoon** [comment]
Implemented and created pull request
