### ISSUE TITLE
[New Feature]: Configurable sensor filters in query triggers

### ISSUE THREAD

**Issue by LucaCinquini** [nasa/opera-sds-pcm#256]
### Checked for duplicates

No - I haven't checked

### Alternatives considered

Yes - and alternatives don't suffice

### Related problems

For Release 1, the current instructions from the project are to process data from Landsat 8 and 9 while testing, but it is still unclear whether we will be required to do this in production, as the funding agency first needs to approve the increased cloud costs. So we might beed to turn off L9 production before the start of operations.

### Describe the feature request

Directly from David B.:
"If possible i would strongly recommend the ability for us to have a filter in the SDS processing that allows us to limit the sensors; e.g. Landsat 8, Landsat 9, Sentinel-2A, Sentinel-2B. This would make it extensible in future to other sensors as well such as S2 C-D  etc; it would allow for phasing of processing for e.g. Landsat 9 and for e.g. Steven to do some spot calval on L9 alone; or a reprocessing of there is a sensor specific issue that gets identified etc. I would recommend this for all our pipelines to have this ability to filter in future too. | If possible i would strongly recommend the ability for us to have a filter in the SDS processing that allows us to limit the sensors; e.g. Landsat 8, Landsat 9, Sentinel-2A, Sentinel-2B. This would make it extensible in future to other sensors as well such as S2 C-D  etc; it would allow for phasing of processing for e.g. Landsat 9 and for e.g. Steven to do some spot calval on L9 alone; or a reprocessing of there is a sensor specific issue that gets identified etc. I would recommend this for all our pipelines to have this ability to filter in future too.
If possible i would strongly recommend the ability for us to have a filter in the SDS processing that allows us to limit the sensors; e.g. Landsat 8, Landsat 9, Sentinel-2A, Sentinel-2B. This would make it extensible in future to other sensors as well such as S2 C-D  etc; it would allow for phasing of processing for e.g. Landsat 9 and for e.g. Steven to do some spot calval on L9 alone; or a reprocessing of there is a sensor specific issue that gets identified etc. I would recommend this for all our pipelines to have this ability to filter in future too."

**Comment by LucaCinquini** [comment]
This is already done in the file settings.yaml file, which can be changed and shipped to all the workers without redeploying.

**Comment by hhlee445** [comment]
Sensor filters configuration has been already implemented.
