### ISSUE TITLE
[New Feature]: Benchmarking on different instance types

### ISSUE THREAD

**Issue by LucaCinquini** [nasa/opera-sds-pcm#257]
### Checked for duplicates

No - I haven't checked

### Alternatives considered

Yes - and alternatives don't suffice

### Describe the feature request

We were asked (during the R1-ORR and R2-SADR) to test the generation of products using different instance types. This phase needs to become an integral part of our development and release process.
During one of our meeting, we discussed that this could be achieved by using one of the existing scripts that Chris wrote, and adding a final step at the end that compares the generated output to the expected output. We would run each algorithm on the golden dataset using different EC2 types.

**Comment by maseca** [comment]
https://wiki.jpl.nasa.gov/display/operasds/L3_DSWx_HLS_PGE+Benchmarking
