### ISSUE TITLE
[New Feature]: Persist the Elasticsearch database across re-deployments

### ISSUE THREAD

**Issue by LucaCinquini** [nasa/opera-sds-pcm#262]
### Checked for duplicates

Yes - I've already checked

### Alternatives considered

No - I haven't considered

### Related problems

During CalVal operations, we need to retain searching and access of the previous products, in case the SDS is redeployed for any reason.

### Describe the feature request

We discussed having a flag that prevents redeploying Elasticsearch, if possible. If not, we need to develop a procedure for backup up and restoring the Elasticsearch state.

**Comment by LucaCinquini** [comment]
Phil:
Here's my thought on why we can't preserve the ES by just not touching the ES server during re-deployments. The infrastructure is code and in any given code change, any of the component can change in any way. Some examples for ES specifically might be:
Updated machine image due to security patching or added service. This happens quite frequently.
different IP address/subnet/etc
different EC2 instance
upgrading ES service
Change of the ES schema (would be rare and we'd have to write some code to convert data)
etc
For these reasons I believe the only way to preserve ES data between re-deployments is to backing up and restoring and not having a flag in the terraform to leave alone ES server.

**Comment by LucaCinquini** [comment]
Then perhaps Nick needs to perfect his existing script for backup and restore of Elasticsearch

**Comment by philipjyoon** [comment]
We've been doing this over a year now.
