### ISSUE TITLE
[New Feature]:  Combine data ingest and ISL purge operations for SLC data download 

### ISSUE THREAD

**Issue by hhlee445** [nasa/opera-sds-pcm#278]
### Checked for duplicates

Yes - I've already checked

### Alternatives considered

No - I haven't considered

### Describe the feature request

We want to combine data ingest and ISL purge operations for SLC data download from ASF DAAC as we did for HLS data download.  We also need to add a step for ORBIT file retrieval using a SLC SAFE ZIP file and ingest.

**Comment by riverma** [comment]
Couple questions:
- Other than querying CMR, can we confirm only a single job that encases downloading products, extracting, ingesting?
- Is the ORBIT file download part of the above job?

**Comment by riverma** [comment]
Hey @hhlee445 - could you help with the above questions when you get a chance?

**Comment by hhlee445** [comment]
1. A single job that encases downloading products, extracting, ingesting, we still need to use a CMR query with --native-id parameter. 
2. Orbit file download is part of downloading a SLC file
