### ISSUE TITLE
Fix failing smoke tests

### ISSUE THREAD

**Issue by chrisjrd** [nasa/opera-sds-pcm#283]
increase timeouts for smoke tests to reduce failure rate.

Currently, smoke tests fail due to timeouts being to low on CI/CD environment. Increase timeouts to observe passing tests.

**Comment by chrisjrd** [comment]
smoke tests fail because mozart API is not storing and returning job IDs properly. pele service is not running. figaro UI does not display new jobs in CI environment.

pele.log file reveals that issue is caused by pele/bach incompatibility due to breaking change in Flask/werkzeug dependency.

Solution may be to pin 2.0.x version in bach-api setup.py rather than 2.1.x

**Comment by riverma** [comment]
OK - yeah curious to see if reverting to 2.0.x removes this issue...

**Comment by chrisjrd** [comment]
pinning the older version has allowed pele and bach-api to run upon deployment. Tests still fail.
We found that disk utilization is at 100% on mozart instance.
Partially caused by the large test-files that get downloaded as part of build+deployment.
I'll address this by adding increasing the disk size as configured in terraform script main.tf

Separately, we should review disk usage by the terraform scripts (delete test files as last deployment step, remove any unnecessary download procedures, etc).

We should also review any instance type we had previously increased before we knew about being able to increase disk size without changing instance types.

There is also an issue with the python environment the cluster sets up. bach-api and pele (or any other distinct service) should have their own python environments. this is a common practice in other teams/orgs when managing python applications.

**Comment by riverma** [comment]
@chrisjrd - we should set up alerts for OPS to be able to be notified in critical disk situations like this.

What's the best way for @niarenaw to monitor disk-usage on Mozart in an operational setting? Are these disk metrics reported to Kabana and can we set up an alert if above 90% disk usage?
