### ISSUE TITLE
Remove download check from daac data subscriber. Raise exceptions instead of continuing

### ISSUE THREAD

**Issue by chrisjrd** [nasa/opera-sds-pcm#288]
The system marks an hls_catalog document as downloaded when it is downloaded to the local machine.
This poses problems on retried jobs when an exception is thrown after that mark.

To address this problem, we must remove the download checks performed by the system. There are 2 known checks that are performed, but there may be more.
1. The daac data subscriber checks download status when getting the list of pending downloads
2. The daac data subscriber checks download status prior to downloading each file.

The daac data subscriber should also fail an entire batch when encountering an exception. And so we must replace a `continue` statement in the loop that downloads files with a `raise` or similar construct that allows exceptions to bubble up.

**Comment by riverma** [comment]
Hey @chrisjrd - I understand these checks are causing other issues, but what if a download actually fails? What mechanism will catch that? In other words - the checks being removed here have alternative checks where exactly?

**Comment by chrisjrd** [comment]
job failures are caught at the hysds level. the check we're doing is redundant, so there is no alternative needed.

**Comment by riverma** [comment]
Ah - got it. So a download failure means the job overall fails, thus we catch it via HySDS.
