### ISSUE TITLE
Improve disk space management in download workers

### ISSUE THREAD

**Issue by chrisjrd** [nasa/opera-sds-pcm#292]
During testing, it was discovered that the use of tile ID for batching download jobs may result in download workers that are assigned more data to download and process than there is disk space. This was causing job failure due to exhausted disk space.

To address this, we need to update the download job to clear the downloaded files upon successful metadata extraction / local dataset creation per dataset. That is, perform cleanup per dataset rather than once at the end of the batch, because the batch may be too large for the running instance to accommodate.

Things to pay attention to:
* disk_usage and similar params in the job spec
* assigned disk space in EC2 instance definition in terraform. Search for "root_dev_size" and "data_dev_size"

**Comment by riverma** [comment]
Hey @chrisjrd - does this ticket imply we are downloading & ETL'ing more than 1 granule per job now?
