### ISSUE TITLE
Add support for Restituted Orbit files to stage_orbit_file.py

### ISSUE THREAD

**Issue by collinss-jpl** [nasa/opera-sds-pcm#318]
In its current version, `stage_orbit_file.py` only supports querying for Precise Orbit Ephemeris (POEORB) files, which will typically only be available for historical processing. Support must be added to query for Restituted Orbit Files (RESORB), which should be available during regular keep-up processing.

**Comment by riverma** [comment]
@collinss-jpl - there was some work done in ARIA on obtaining precise orbit and restituted orbits.

Take a look at:
- https://github.com/aria-jpl/coseismic_enumerator/blob/cc67912bf843b88d52138bf1d768e3fa6fa0da8b/orbit.py#L46
- https://github.com/aria-jpl/coseismic_enumerator/blob/038ad02a9897e432679e5fd1f8f8bdf01798f7c6/es/request.py#L141

Or more generally the repository: https://github.com/aria-jpl/coseismic_enumerator
