### ISSUE TITLE
Benchmark EC2 instance types for use with PGE job

### ISSUE THREAD

**Issue by chrisjrd** [nasa/opera-sds-pcm#335]

**Comment by chrisjrd** [comment]
Report -- https://wiki.jpl.nasa.gov/display/operasds/OPERA+SDS+PCM+Release+1+Benchmarking+Report

Data spreadsheet -- https://docs.google.com/spreadsheets/d/1PMxX2Bm4QhYkn3rZG1NbsXjN0W03GMog/edit?usp=share_link&ouid=117541312444035309585&rtpof=true&sd=true

**Comment by hhlee445** [comment]
DSWx-HLS sciflo EC2 instance types have been updated as the result of benchmarking report.
