### ISSUE TITLE
[New Feature]: Update a trigger rule for RTC PGE execution

### ISSUE THREAD

**Issue by hhlee445** [nasa/opera-sds-pcm#377]
### Checked for duplicates

Yes - I've already checked

### Alternatives considered

No - I haven't considered

### Describe the feature request

We don't want to trigger a RTC SCIFLO job when the processing mode is in historical processing. 
Need to update a trigger rule for RTC SCIFLO with processing mode check.

**Comment by philipjyoon** [comment]
Resolved as part of https://github.com/nasa/opera-sds-pcm/issues/392
