### ISSUE TITLE
Soft timer limit is too short for RTC PGE

### ISSUE THREAD

**Issue by philipjyoon** [nasa/opera-sds-pcm#383]
### Checked for duplicates

Yes - I've already checked

### Describe the bug

Currently the soft timer limit for RTC PGE is 14400 seconds which is 4 hours. We are seeing that some files require more than that time. We had been told that SLC should take 3-4 hrs. We will add one more hour to make it 5 hrs to add buffer and test.

### What did you expect?

SLC PGE to run to completion without errors.

### Reproducible steps

```bash
1.
2.
3.
...
```

### Environment

```bash
Release 2 ER 2
```

**Comment by hhlee445** [comment]
The RTC PGE execution took about 3084 secs after changing the EC2 instance type from c5a.large to c6a.2xlarge.  So there is no need to change the soft time limit.
