### ISSUE TITLE
SLC download error w R2 RC4 tag - json_parse_exception

### ISSUE THREAD

**Issue by philipjyoon** [nasa/opera-sds-pcm#427]
### Checked for duplicates

Yes - I've already checked

### Describe the bug

python daac_data_subscriber.py query -c SENTINEL-1A_SLC --release-version=2.0.0-rc.4.0 --native-id=S1A_IW_SLC__1SDV_20200801T002636_20200801T002704_033706_03E810_6306-SLC --chunk-size=1 --job-queue=opera-job_worker-slc_data_download

Exception below in comment

### What did you expect?

I expected it to work

**Comment by philipjyoon** [comment]
Traceback (most recent call last):
File "/home/ops/verdi/ops/hysds-1.1.10/hysds/dataset_ingest_bulk.py", line 900, in publish_datasets
bulk_index_dataset(app.conf.GRQ_UPDATE_URL_BULK, prod_jsons)
File "/home/ops/verdi/lib/python3.9/site-packages/backoff/_sync.py", line 105, in retry
ret = target(*args, **kwargs)
File "/home/ops/verdi/ops/hysds-1.1.10/hysds/dataset_ingest_bulk.py", line 750, in bulk_index_dataset
raise NotAllProductsIngested(r.text)
hysds.dataset_ingest_bulk.NotAllProductsIngested: {"success": false, "message": "[{'index': {'_index': 'grq_1_l1_s1_slc', '_type': '_doc', '_id': 'S1A_IW_SLC__1SDV_20200801T002636_20200801T002704_033706_03E810_6306', 'status': 400, 'error': {'type': 'parse_exception', 'reason': 'Failed to parse content to map', 'caused_by': {'type': 'json_parse_exception', 'reason': \"Non-standard token 'Infinity': enable JsonParser.Feature.ALLOW_NON_NUMERIC_NUMBERS to allow\\n at [Source: (org.elasticsearch.common.bytes.AbstractBytesReference$MarkSupportingStreamInputWrapper); line: 1, column: 992]\"}}}}]", "objectid": null, "index": null}


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/ops/verdi/ops/hysds-1.1.10/hysds/job_worker.py", line 1410, in run_job
post_processor_sigs.append(func(job, context))
File "/home/ops/verdi/ops/hysds-1.1.10/hysds/dataset_ingest_bulk.py", line 909, in publish_datasets
raise NotAllProductsIngested("Products failed to index to elasticsearch: %s" % traceback.format_exc())
hysds.dataset_ingest_bulk.NotAllProductsIngested: Products failed to index to elasticsearch: Traceback (most recent call last):
File "/home/ops/verdi/ops/hysds-1.1.10/hysds/dataset_ingest_bulk.py", line 900, in publish_datasets
bulk_index_dataset(app.conf.GRQ_UPDATE_URL_BULK, prod_jsons)
File "/home/ops/verdi/lib/python3.9/site-packages/backoff/_sync.py", line 105, in retry
ret = target(*args, **kwargs)
File "/home/ops/verdi/ops/hysds-1.1.10/hysds/dataset_ingest_bulk.py", line 750, in bulk_index_dataset
raise NotAllProductsIngested(r.text)
hysds.dataset_ingest_bulk.NotAllProductsIngested: {"success": false, "message": "[{'index': {'_index': 'grq_1_l1_s1_slc', '_type': '_doc', '_id': 'S1A_IW_SLC__1SDV_20200801T002636_20200801T002704_033706_03E810_6306', 'status': 400, 'error': {'type': 'parse_exception', 'reason': 'Failed to parse content to map', 'caused_by': {'type': 'json_parse_exception', 'reason': \"Non-standard token 'Infinity': enable JsonParser.Feature.ALLOW_NON_NUMERIC_NUMBERS to allow\\n at [Source: (org.elasticsearch.common.bytes.AbstractBytesReference$MarkSupportingStreamInputWrapper); line: 1, column: 992]\"}}}}]", "objectid": null, "index": null}

**Comment by hhlee445** [comment]
This error is no longer appear in 2.0.0-RC.10
