### ISSUE TITLE
[Bug]: stage_dem.py does not account for margin before performing anti-meridian check

### ISSUE THREAD

**Issue by collinss-jpl** [nasa/opera-sds-pcm#445]
### Checked for duplicates

Yes - I've already checked

### Describe the bug

DEM's that are staged for certain HLS tiles near, but not crossing the anti-merdian, are not staged with the proper amount of margin to satisfy the overlap check perfomed by the SAS. The underlying cause is that the designated margin in KM is not accounted for when preforming the check to see if a DEM/HLS region crosses the anti-meridian _after_ the margin is applied.

### What did you expect?

The stage_dem.py script needs to be updated to properly split a staged DEM across the anti-meridian when DEM regions cross it _after_ the margin has been applied.

### Reproducible steps

```bash
Submit a DSWx-HLS job in PCM using an HLS product with the T60WWD tile. This job should fail due to the DEM overlap check performed in the SAS.
```

### Environment

```bash
- Version of this software [e.g. vX.Y.Z]
- Operating System: [e.g. MacOSX with Docker Desktop vX.Y]
...
```

**Comment by toandn-jpl** [comment]
adding failing trace for I&T/OPS reference:

[triaged_job-SCIFLO_L3_DSWx_HLS__2.0.0-rc.4.0-HLS.S30.T01WCN.2020111T232629.v2.0-20230329T210008.957493Z_failed_stderr.txt](https://github.com/nasa/opera-sds-pcm/files/11106727/triaged_job-SCIFLO_L3_DSWx_HLS__2.0.0-rc.4.0-HLS.S30.T01WCN.2020111T232629.v2.0-20230329T210008.957493Z_failed_stderr.txt)
