### ISSUE TITLE
[Bug]: Query jobs may reprocess data. Temporal start date needs rolling window of margin

### ISSUE THREAD

**Issue by chrisjrd** [nasa/opera-sds-pcm#453]
### Checked for duplicates

Yes - I've already checked

### Describe the bug

We note that the system may ingest the same HLS data if it has been updated by the CMR. This can happen because the updated data will be returned in future queries and processed accordingly. If the data has expired from rolling storage (default 15 day retention period), the data is then ingested and processing continues.

This "reprocessing" is not accounted/budgeted for.

### What did you expect?

We expect OPERA SDS PCM to not reprocess data when in "forward" processing mode.

### Reproducible steps

```bash
1. Query CMR for data.
2. Process data.
3. Wait some time: weeks, months, years.
4. Query CMR for data.
5. Observe that previously processed data is reprocessed.
```

### Environment

```bash
- All
```

**Comment by hhlee445** [comment]
This fix was made in https://github.com/nasa/opera-sds-lambdas/pull/29
