### ISSUE TITLE
[New Feature]: Print quantity of SLC products during subscriber query and filter on IW band products

### ISSUE THREAD

**Issue by maseca** [nasa/opera-sds-pcm#462]
### Checked for duplicates

Yes - I've already checked

### Alternatives considered

Yes - and alternatives don't suffice

### Describe the feature request

Print quantity of SLC products during subscriber query and filter on IW band products.
Ingest only IW band SLC product information to slc_catalog and slc_spatial_catalog.

**Comment by hhlee445** [comment]
You can test with **`-s 2023-05-02T16:13:00Z -e 2023-05-02T16:15:00Z`** time range. 4 SLC product:  3 IW beam mode and 1 non-IW beam mode.
