### ISSUE TITLE
[Bug]: Forward processing lambda does not work in 2.0.0-rc.7.0

### ISSUE THREAD

**Issue by philipjyoon** [nasa/opera-sds-pcm#507]
### Checked for duplicates

Yes - I've already checked

### Describe the bug

Fails w the following error:

[ERROR] Runtime.ImportModuleError: Unable to import module 'lambda_function': urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with OpenSSL 1.0.2k-fips  26 Jan 2017. See: https://github.com/urllib3/urllib3/issues/2168
Traceback (most recent call last):

### What did you expect?

I expected it to work

### Reproducible steps

```bash
1. Enable HLS L or HLS L lambda query timer 
2. Observe that no HLS query jobs get created in Figaro
3.
...
```

### Environment

```bash
2.0.0-rc.7.0
```

**Comment by philipjyoon** [comment]
This error occurs for both HLS and SLC lambda functions. (It's the same function). Turns out the error is benign - the query jobs do get queued up despite this error for both HLS and SLC.

@hhlee445 reports that these errors do not come out with the hySDS version 5

**Comment by philipjyoon** [comment]
The error is may or may NOT be benign. Regardless of this error the forward processing of HLS does not work in R2 RC7. No query jobs ever get scheduled in the PCM when the lambda is enabled.

**Comment by philipjyoon** [comment]
The lambda timers are working correctly in the newest develop branch as of May 31, 2023
https://github.com/nasa/opera-sds-pcm/commit/b7311a4cba11313d8a44551a565e88209e562cb7

**Comment by philipjyoon** [comment]
Tested 2.0.0-rc.6.0 on INT-POP1 and the HLS lambdas work correctly.

Destroyed that cluster and deployed 2.0.0-rc.7.0 also on INT-POP1 and the HLS lambdas do not work, consistent with the original finding.

The lambda repo for 6.0 and 7.0 are identical. On the pcm repo there doesn't seem to be any differences that explains this difference.

**Comment by hhlee445** [comment]
urllib version needs to be set. The fix is made on issue_478.
