### ISSUE TITLE
Split DAAC query and retrieval execution

### ISSUE THREAD

**Issue by hhlee445** [nasa/opera-sds-pcm#51]
### Checked for duplicates

Yes - I've already checked

### Alternatives considered

Yes - and alternatives don't suffice

### Describe the feature request

Current data-subscriber script queries DAAC CMR and retrieves the data into our S3 bucket within one script. 
We should split the querying and retrieving functions in separate scripts so that  a querying script can be executed by a factotum worker and a retrieving script can be executed by many verdi workers.

**Comment by hhlee445** [comment]
- Add download timestamp in the ES
- Consolidate log messages from _stdout.txt into the subscriber.log
- The log messages from the data subscriber python script don't included in the subscriber.log

**Comment by maseca** [comment]
I have added the timestamp and removed the subscriber.log file in favor of printing everything to stdout. Could you please let me know which log messages are still missing if any?

**Comment by maseca** [comment]
Expected output in _stdout.txt may be found in _stderr.txt. I'm in favor of keeping the outputs separate as _stdout.txt contains the top level logs (~3K) and _stderr.txt contains all of the lower level logs (~20M).
