### ISSUE TITLE
[Bug]: Error with query timer lambda function

### ISSUE THREAD

**Issue by hhlee445** [nasa/opera-sds-pcm#524]
### Checked for duplicates

Yes - I've already checked

### Describe the bug

When I enabled the query timer, it raised an error as 

[ERROR] Runtime.ImportModuleError: Unable to import module 'lambda_function': urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'OpenSSL 1.0.2k-fips

### What did you expect?

We expect to have query timer execute successfully without an error.

### Environment

```bash
- Version of this software [e.g. vX.Y.Z]
- Operating System: [e.g. MacOSX with Docker Desktop vX.Y]
...
```

**Comment by chrisjrd** [comment]
issue addressed here https://github.com/nasa/opera-sds-lambdas/pull/33
