### ISSUE TITLE
[New Feature]: Blue / Green Deployment for PCM

### ISSUE THREAD

**Issue by riverma** [nasa/opera-sds-pcm#528]
### Checked for duplicates

Yes - I've already checked

### Alternatives considered

Yes - and alternatives don't suffice

### Related problems

Currently, the PCM deployment procedure requires our system to be offline during a major PCM upgrade. This downtime amount will only increase in duration as more complex and longer-running PGEs are active in our system - since we'd want to wait for processing to complete before an upgrade commences. 

### Describe the feature request

We should design, ascertain the cost, and eventually implement a "blue / green" deployment system or procedure that ensure our PCM has zero downtime during upgrades.

**Comment by riverma** [comment]
## Operational Needs

Assuming "blue" is the legacy system, and "green" is the new system:

1. (**Required**) Zero operational downtime between "blue" wind-down and "green" wind-up
2. (**Required**) Ability to revert to using "blue" should "green" be problematic
3. (**Required**) Maintaining interface agreements with external systems such that the data flow in or out with respect to "blue" or "green" is maintained
4. (Desired) Operational state is maintained between "blue" and "green"

**Comment by hhlee445** [comment]
OPERA SDS doesn't need to keep the current states of the processes. So we don't need to perform blue/green deployment when upgrading to newer version.
