### ISSUE TITLE
[New Feature]: Static layer toggle for CSLC-S1 historical processing

### ISSUE THREAD

**Issue by collinss-jpl** [nasa/opera-sds-pcm#540]
### Checked for duplicates

Yes - I've already checked

### Alternatives considered

Yes - and alternatives don't suffice

### Related problems

Currently for the CSLC-S1 PGE, there is only a single toggle flag to enable or disable static layer generation. This makes it difficult to have layer generation enabled for one processing mode, but not the other. Static layer generation should typically never be enabled for Historical processing, only Forward.

### Describe the feature request

~We need separate flags in settings.yaml to control static layer generation independently between forward and historical processing modes.~
When processing CSLC in any mode besides Forward, static layer generation should always be set to False.

**Comment by hhlee445** [comment]
Fixed https://github.com/nasa/opera-sds-pcm/pull/557
