### ISSUE TITLE
[Bug]: Insufficient DEM margin at high latitudes

### ISSUE THREAD

**Issue by collinss-jpl** [nasa/opera-sds-pcm#550]
### Checked for duplicates

Yes - I've already checked

### Describe the bug

For certain SLC archives captured at a high latitude, the simple application of margin applied to the bounding box provided to stage_dem.py is insufficient to properly cover the extent of the SLC region.

### What did you expect?

For SLC archives captured at high latitude (>75), the margin applied should take latitude into account, and apply the correct amount.

### Reproducible steps
Testing with the following SLC archives should be sufficient to both reproduce the error, and ensure that the fix applies the correct amount of margin:

- S1A_IW_SLC__1SDH_20230628T122459_20230628T122529_049186_05EA1E_AD77
- S1A_IW_SLC__1SDH_20230628T122527_20230628T122546_049186_05EA1E_4B0C
- S1A_IW_SLC__1SDH_20230628T122652_20230628T122722_049186_05EA20_0BC9

### Environment

```bash
- Version of this software [e.g. vX.Y.Z]
- Operating System: [e.g. MacOSX with Docker Desktop vX.Y]
...
```

**Comment by hhlee445** [comment]
Fixed  https://github.com/nasa/opera-sds-pcm/pull/555
