### ISSUE TITLE
[New Feature]: Optimizing Elasticsearch

### ISSUE THREAD

**Issue by riverma** [nasa/opera-sds-pcm#562]
### Checked for duplicates

Yes - I've already checked

### Alternatives considered

Yes - and alternatives don't suffice

### Related problems

@hookhua made a series of recommendations for optimizing interactions with HySDS Elasticsearch deployments (i.e. Mozart, GRQ, Metrics). We want to do an audit of Elasticsearch deployments to ensure we’re in line with the checklist of optimizations. As we approach a significantly larger processing volume for OPERA R3, we should have optimizations in place.

### Describe the feature request

Recommending performing an audit and creating separate tickets for the following optimizations that need to be implemented:

| Optimization Name                                      | Optimization Description |
|:--------------------------------------------- |:-------- |
| Jittering                                     | All API calls have randomized jittering, e.g., calls to ES API. This feature is implemented in adaptation code and not limited to hysds-core. |
| Exponential Backoff                           | All API calls have randomized exponential backoff, e.g., calls to ES API. This feature is implemented in adaptation code and not limited to hysds-core. |
| Reduce ES Doc Size                            | Ensure the entire ES document stores only necessary data. Refer to the Elastic documentation for guidance on [reducing document size](https://www.elastic.co/guide/en/elasticsearch/reference/current/general-recommendations.html#large-size). |
| Pagination Search                             | For deep pagination cases, avoid using the scroll API. Instead, use the search_after parameter with a point in time (PIT) to preserve the index state while paging through more than 10,000 hits. Refer to the Elastic documentation on [paginating search results](https://www.elastic.co/guide/en/elasticsearch/reference/current/paginate-search-results.html#scroll-search-results) for details. |
| Search with Rounded Dates                     | Utilize rounded dates in Elasticsearch searches to improve search speed. For more information, refer to the Elastic documentation on [tuning search speed](https://www.elastic.co/guide/en/elasticsearch/reference/current/tune-for-search-speed.html#_search_rounded_dates). |
| Delete Indices, Not Documents                 | When managing Elasticsearch indices, consider deleting indices instead of individual documents. Refer to the Elastic documentation on [index management](https://www.elastic.co/guide/en/elasticsearch/reference/current/size-your-shards.html#delete-indices-not-documents) for best practices. Keep in mind that the delete operation marks data as deletable until garbage collection occurs. |
| ILM Life-Cycle Management to Roll Off Old Indices | Implement Index Lifecycle Management (ILM) to automatically roll off old indices in Elasticsearch. Refer to the Elastic documentation on [index lifecycle management](https://www.elastic.co/guide/en/elasticsearch/reference/current/index-lifecycle-management.html#index-lifecycle-management) and [deleting empty indices](https://www.elastic.co/guide/en/elasticsearch/reference/current/size-your-shards.html#delete-empty-indices) for detailed guidance. |
| Node Optimization                            | Consider having 3 master nodes for optimal Elasticsearch performance. If performance is satisfactory with 2 nodes, you may experiment by downgrading instance sizes. Start with xlarge or large instances for testing and easily scale up as needed. |
| Sharding Strategy: ~10GB to 50GB per Shard    | Implement a sharding strategy that allocates approximately 10GB to 50GB of data per shard. Avoid oversharding your indices to optimize Elasticsearch performance. For more information, consult the Elastic documentation on [shard sizing](https://www.elastic.co/guide/en/elasticsearch/reference/current/size-your-shards.html#size-your-shards). Each index in Elasticsearch is divided into one or more shards, each of which may be replicated across multiple nodes to protect against hardware failures. |
| Replica Tuning                               | Consider adjusting replica settings to enhance search throughput in Elasticsearch. For more information, refer to the Elastic documentation on [tuning search speed](https://www.elastic.co/guide/en/elasticsearch/reference/current/tune-for-search-speed.html#_replicas_might_help_with_throughput_but_not_always). |
| File System Caching                          | Leveraging the underlying file system's cache to optimize data retrieval and improve search performance. |
| Use Built-in Auto-generated IDs              | Utilize built-in auto-generated IDs for Elasticsearch documents. For details on how to use this feature, consult the Elastic documentation on [tuning search speed](https://www.elastic.co/guide/en/elasticsearch/reference/current/tune-for-search-speed.html#_search_rounded_dates). |
| Enough RAM?                                 | Ensure that your Elasticsearch data nodes have sufficient RAM to support your workload. Refer to the Elastic documentation on [tuning KNN search](https://www.elastic.co/guide/en/elasticsearch/reference/current/tune-knn-search.html#_ensure_data_nodes_have_enough_memory) for recommendations. |
| Use Larger ES Nodes                         | Consider utilizing larger Elasticsearch nodes to improve indexing speed. For further information, refer to the Elastic documentation on [tuning indexing speed](https://www.elastic.co/guide/en/elasticsearch/reference/current/tune-for-indexing-speed.html#_use_faster_hardware). |

**Comment by hookhua** [comment]
In addition to the above listed, one other thing discussed on SWOT and NISAR is reconfiguring the three separate ES instances into a single 3-node ES cluster. This would allow ES to better load balance the queries while not significantly increase the ES resource footprint.

Separate still, there are also a few updates to hysds-core that may help as well that SWOT and NISAR are looking into. For example:
- Make user dataset rule evaluation more efficient/targetted https://hysds-core.atlassian.net/browse/HC-476
- Make User Rule Job evaluation more targeted https://hysds-core.atlassian.net/browse/HC-482

**Comment by riverma** [comment]
In addition to what @hookhua mentioned, we should also evaluate our mapping of nodes to shards. Currently we have multiple shards with a single node, which can actually cause ES to perform _slower_ than single node / single shard. If we don't have multiple nodes, having multiples shards doesn't really give us much!

**Comment by riverma** [comment]
Hey @hhlee445 - OpenSearch will enable some of the features above but an upgrade alone won't resolve all of these. Suggest keeping this ticket open or migrating these feature requests to a new open search ticket.
