### ISSUE TITLE
[Bug]: 29 granules failed RTC processing from edge case list likely due to DEM stage margin

### ISSUE THREAD

**Issue by philipjyoon** [nasa/opera-sds-pcm#593]
### Checked for duplicates

Yes - I've already checked

### Describe the bug

The following SCIFLO jobs (from which the granule IDs can be extracted) failed during R2 RC10 edge case testing. There are 29 static and non-static pairs resulting 58 items below.

SCIFLO_L2_RTC_S1__2.0.0-rc.10.0-S1B_IW_SLC__1SDV_20210706T183013_20210706T183043_027677_034D9B_576E-r6-20230823T162346.224184Z
SCIFLO_L2_RTC_S1__2.0.0-rc.10.0-S1B_IW_SLC__1SDV_20210706T183040_20210706T183108_027677_034D9B_1466-r6-20230823T162321.572125Z
SCIFLO_L2_RTC_S1__2.0.0-rc.10.0-S1A_IW_SLC__1SDV_20210717T063224_20210717T063300_038813_04946E_8746-r10-20230823T162206.61990Z
SCIFLO_L2_RTC_S1__2.0.0-rc.10.0-S1A_IW_SLC__1SDV_20210706T055355_20210706T055431_038653_048FA4_BF54-r10-20230823T162213.36927Z
SCIFLO_L2_RTC_S1__2.0.0-rc.10.0-S1B_IW_SLC__1SDV_20210706T183106_20210706T183133_027677_034D9B_C457-r6-20230823T162308.334534Z
SCIFLO_L2_RTC_S1__2.0.0-rc.10.0-S1A_IW_SLC__1SDV_20210730T055357_20210730T055432_039003_049A16_947A-r9-20230823T162158.485858Z
SCIFLO_L2_RTC_S1__2.0.0-rc.10.0-S1A_IW_SLC__1SDV_20210722T173220_20210722T173250_038893_0496DD_4CB3-r8-20230823T162134.123350Z
SCIFLO_L2_RTC_S1__2.0.0-rc.10.0-S1A_IW_SLC__1SDV_20210729T063225_20210729T063300_038988_0499A0_E92F-r10-20230823T162200.296121Z
SCIFLO_L2_RTC_S1__2.0.0-rc.10.0-S1A_IW_SLC__1SDV_20210705T063224_20210705T063259_038638_048F31_72BD-r8-20230823T162212.921228Z
SCIFLO_L2_RTC_S1__2.0.0-rc.10.0-S1B_IW_SLC__1SDV_20210718T183132_20210718T183144_027852_0352CE_CDDA-r6-20230823T162143.558112Z
SCIFLO_L2_RTC_S1__2.0.0-rc.10.0-S1B_IW_SLC__1SDV_20210718T183041_20210718T183109_027852_0352CE_795B-r6-20230823T162254.650074Z
SCIFLO_L2_RTC_S1__2.0.0-rc.10.0-S1B_IW_SLC__1SDV_20210730T183014_20210730T183044_028027_0357ED_4B46-r6-20230823T162237.829599Z
SCIFLO_L2_RTC_S1__2.0.0-rc.10.0-S1B_IW_SLC__1SDV_20210730T183042_20210730T183110_028027_0357ED_A7B7-r6-20230823T162246.117189Z
SCIFLO_L2_RTC_S1__2.0.0-rc.10.0-S1A_IW_SLC__1SDH_20210705T051812_20210705T051842_038638_048F29_C3CC-r8-20230823T162205.845780Z
SCIFLO_L2_RTC_S1__2.0.0-rc.10.0-S1B_IW_SLC__1SDV_20210718T183107_20210718T183134_027852_0352CE_840C-r6-20230823T162241.510278Z
SCIFLO_L2_RTC_S1__2.0.0-rc.10.0-S1B_IW_SLC__1SDV_20210718T183014_20210718T183044_027852_0352CE_5ECF-r6-20230823T162246.523145Z
SCIFLO_L2_RTC_S1__2.0.0-rc.10.0-S1A_IW_SLC__1SDV_20210718T055356_20210718T055431_038828_0494E3_E12C-r10-20230823T162204.239090Z
SCIFLO_L2_RTC_S1__2.0.0-rc.10.0-S1A_IW_SLC__1SDV_20210712T183156_20210712T183226_038748_049285_EB08-r6-20230823T162200.498405Z
SCIFLO_L2_RTC_S1__2.0.0-rc.10.0-S1B_IW_SLC__1SDV_20210730T183133_20210730T183145_028027_0357ED_AE8F-r6-20230823T162130.936269Z
SCIFLO_L2_RTC_S1__2.0.0-rc.10.0-S1A_IW_SLC__1SDH_20210729T051813_20210729T051843_038988_049998_C78C-r9-20230823T162156.282472Z
SCIFLO_L2_RTC_S1__2.0.0-rc.10.0-S1B_IW_SLC__1SDV_20210706T183131_20210706T183143_027677_034D9B_8B38-r6-20230823T162156.627979Z
SCIFLO_L2_RTC_S1__2.0.0-rc.10.0-S1A_IW_SLC__1SDV_20210702T181912_20210702T181936_038602_048E0F_D8FA-r10-20230823T162130.521862Z
SCIFLO_L2_RTC_S1__2.0.0-rc.10.0-S1B_IW_SLC__1SDV_20210730T183108_20210730T183135_028027_0357ED_38AB-r6-20230823T162231.667604Z
SCIFLO_L2_RTC_S1__2.0.0-rc.10.0-S1A_IW_SLC__1SDH_20210717T051813_20210717T051842_038813_049466_8C5E-r9-20230823T162159.82184Z
SCIFLO_L2_RTC_S1__2.0.0-rc.10.0-S1A_IW_SLC__1SDV_20210724T183157_20210724T183227_038923_0497BE_CDD3-r6-20230823T162152.234551Z
SCIFLO_L2_RTC_S1__2.0.0-rc.10.0-S1A_IW_SLC__1SDV_20210724T183224_20210724T183252_038923_0497BE_9731-r6-20230823T162145.375226Z
SCIFLO_L2_RTC_S1__2.0.0-rc.10.0-S1A_IW_SLC__1SDV_20210712T183224_20210712T183251_038748_049285_4C97-r6-20230823T162156.529219Z
SCIFLO_L2_RTC_S1__2.0.0-rc.10.0-S1A_IW_SLC__1SDV_20210710T173220_20210710T173250_038718_0491A0_ABA4-r8-20230823T162152.994831Z
SCIFLO_L2_RTC_S1__2.0.0-rc.10.0-S1A_IW_SLC__1SDV_20210714T181912_20210714T181937_038777_04935C_89D1-r7-20230823T162123.177830Z
SCIFLO_L2_RTC_S1__2.0.0-rc.10.0-S1B_IW_SLC__1SDV_20210730T183014_20210730T183044_028027_0357ED_4B46-r6-20230818T212933.228178Z
SCIFLO_L2_RTC_S1__2.0.0-rc.10.0-S1B_IW_SLC__1SDV_20210718T183107_20210718T183134_027852_0352CE_840C-r6-20230818T212919.433429Z
SCIFLO_L2_RTC_S1__2.0.0-rc.10.0-S1B_IW_SLC__1SDV_20210718T183041_20210718T183109_027852_0352CE_795B-r6-20230818T212931.743153Z
SCIFLO_L2_RTC_S1__2.0.0-rc.10.0-S1B_IW_SLC__1SDV_20210706T183013_20210706T183043_027677_034D9B_576E-r6-20230818T212935.425355Z
SCIFLO_L2_RTC_S1__2.0.0-rc.10.0-S1B_IW_SLC__1SDV_20210706T183040_20210706T183108_027677_034D9B_1466-r6-20230818T212945.645616Z
SCIFLO_L2_RTC_S1__2.0.0-rc.10.0-S1B_IW_SLC__1SDV_20210730T183042_20210730T183110_028027_0357ED_A7B7-r6-20230818T212934.193893Z
SCIFLO_L2_RTC_S1__2.0.0-rc.10.0-S1B_IW_SLC__1SDV_20210730T183108_20210730T183135_028027_0357ED_38AB-r6-20230818T212918.5041Z
SCIFLO_L2_RTC_S1__2.0.0-rc.10.0-S1B_IW_SLC__1SDV_20210718T183014_20210718T183044_027852_0352CE_5ECF-r6-20230818T212928.369925Z
SCIFLO_L2_RTC_S1__2.0.0-rc.10.0-S1B_IW_SLC__1SDV_20210706T183106_20210706T183133_027677_034D9B_C457-r6-20230818T212922.6035Z
SCIFLO_L2_RTC_S1__2.0.0-rc.10.0-S1B_IW_SLC__1SDV_20210718T183132_20210718T183144_027852_0352CE_CDDA-r6-20230818T212828.765172Z
SCIFLO_L2_RTC_S1__2.0.0-rc.10.0-S1A_IW_SLC__1SDV_20210712T183156_20210712T183226_038748_049285_EB08-r6-20230818T212721.692332Z
SCIFLO_L2_RTC_S1__2.0.0-rc.10.0-S1A_IW_SLC__1SDV_20210712T183224_20210712T183251_038748_049285_4C97-r6-20230818T212708.183600Z
SCIFLO_L2_RTC_S1__2.0.0-rc.10.0-S1A_IW_SLC__1SDV_20210710T173220_20210710T173250_038718_0491A0_ABA4-r8-20230818T212710.123143Z
SCIFLO_L2_RTC_S1__2.0.0-rc.10.0-S1A_IW_SLC__1SDV_20210705T063224_20210705T063259_038638_048F31_72BD-r8-20230818T212737.730531Z
SCIFLO_L2_RTC_S1__2.0.0-rc.10.0-S1A_IW_SLC__1SDV_20210706T055355_20210706T055431_038653_048FA4_BF54-r10-20230818T212737.152874Z
SCIFLO_L2_RTC_S1__2.0.0-rc.10.0-S1A_IW_SLC__1SDH_20210705T051812_20210705T051842_038638_048F29_C3CC-r8-20230818T212739.19188Z
SCIFLO_L2_RTC_S1__2.0.0-rc.10.0-S1A_IW_SLC__1SDV_20210702T181912_20210702T181936_038602_048E0F_D8FA-r10-20230818T212707.25510Z
SCIFLO_L2_RTC_S1__2.0.0-rc.10.0-S1A_IW_SLC__1SDV_20210714T181912_20210714T181937_038777_04935C_89D1-r7-20230818T212630.374148Z
SCIFLO_L2_RTC_S1__2.0.0-rc.10.0-S1B_IW_SLC__1SDV_20210730T183133_20210730T183145_028027_0357ED_AE8F-r6-20230818T212637.1498Z
SCIFLO_L2_RTC_S1__2.0.0-rc.10.0-S1B_IW_SLC__1SDV_20210706T183131_20210706T183143_027677_034D9B_8B38-r6-20230818T212827.488558Z
SCIFLO_L2_RTC_S1__2.0.0-rc.10.0-S1A_IW_SLC__1SDV_20210729T063225_20210729T063300_038988_0499A0_E92F-r10-20230818T212509.729650Z
SCIFLO_L2_RTC_S1__2.0.0-rc.10.0-S1A_IW_SLC__1SDV_20210718T055356_20210718T055431_038828_0494E3_E12C-r10-20230818T212500.464501Z
SCIFLO_L2_RTC_S1__2.0.0-rc.10.0-S1A_IW_SLC__1SDV_20210717T063224_20210717T063300_038813_04946E_8746-r10-20230818T212500.109238Z
SCIFLO_L2_RTC_S1__2.0.0-rc.10.0-S1A_IW_SLC__1SDV_20210730T055357_20210730T055432_039003_049A16_947A-r9-20230818T212459.743721Z
SCIFLO_L2_RTC_S1__2.0.0-rc.10.0-S1A_IW_SLC__1SDV_20210724T183157_20210724T183227_038923_0497BE_CDD3-r6-20230818T212453.878484Z
SCIFLO_L2_RTC_S1__2.0.0-rc.10.0-S1A_IW_SLC__1SDH_20210729T051813_20210729T051843_038988_049998_C78C-r9-20230818T212504.714985Z
SCIFLO_L2_RTC_S1__2.0.0-rc.10.0-S1A_IW_SLC__1SDH_20210717T051813_20210717T051842_038813_049466_8C5E-r9-20230818T212457.130070Z
SCIFLO_L2_RTC_S1__2.0.0-rc.10.0-S1A_IW_SLC__1SDV_20210724T183224_20210724T183252_038923_0497BE_9731-r6-20230818T212449.612603Z
SCIFLO_L2_RTC_S1__2.0.0-rc.10.0-S1A_IW_SLC__1SDV_20210722T173220_20210722T173250_038893_0496DD_4CB3-r8-20230818T212442.66214Z

### What did you expect?

n/t

### Reproducible steps

```bash
1.
2.
3.
...
```

### Environment

```bash
- Version of this software [e.g. vX.Y.Z]
- Operating System: [e.g. MacOSX with Docker Desktop vX.Y]
...
```

**Comment by collinss-jpl** [comment]
Closed by #599
