### ISSUE TITLE
[Bug]: BACH-UI on OPS timing out 

### ISSUE THREAD

**Issue by LalaP** [nasa/opera-sds-pcm#602]
### Checked for duplicates

Yes - I've already checked

### Describe the bug

In order to generate a complete set of  accountability reports for OPS team, I started from 1st day of operations (04/11/2023). Generated midnight-to-midnight reports per each day.

This effort started on 08/09/2023  Aug 9th , 2023 Reports (4 per day) generated without any issue and all of a sudden bach-ui started to time out. 
Note there is a time out limit on bach-ui which is set to 30 min. But The time does not seems to be the issue since the period report is created is not long (24 hours).

Bellow you may see the bach-ui after 30 min run:

![Screenshot 2023-08-30 at 4 17 26 PM](https://github.com/nasa/opera-sds-ops/assets/3938017/39ea0f09-0baf-45c1-9a31-e9e2d6165c91)

We also check on the GRQ machine and did not notice anything suspicious on TOP in general. The machien was almost ideal. Yet after running a report we noticed high memory usage.

![264494318-8a1cf142-5927-4987-bd81-396be1193f77](https://github.com/nasa/opera-sds-ops/assets/3129134/afb33736-51e1-4f72-9f78-9ac731561047)

### What did you expect?

I expected to have a report as a result in few minutes (max5) 

### Environment

The OPS venue, specifically: `/bach-ui` end-point

**Comment by hhlee445** [comment]
https://github.com/nasa/opera-sds-pcm/issues/601
