### ISSUE TITLE
[New Feature]: update runtime for harikiri lambda

### ISSUE THREAD

**Issue by chrisjrd** [nasa/opera-sds-pcm#617]
### Checked for duplicates

Yes - I've already checked

### Alternatives considered

Yes - and alternatives don't suffice

### Related problems

AWS is deprecating the python 3.7 lambda runtime in 1/2024

### Describe the feature request

I want to configure the harikiri lambda to run in the python 3.8 runtime

**Comment by hhlee445** [comment]
The change of python version was added
