### ISSUE TITLE
[New Feature]: CSV option for DATA SUMMARY of bach-ui

### ISSUE THREAD

**Issue by LalaP** [nasa/opera-sds-pcm#627]
### Checked for duplicates

Yes - I've already checked

### Alternatives considered

Yes - and alternatives don't suffice

### Related problems

There have been situations that OPS team wanted to list the files that have not had PUBLISHED status. Yet unable to extract the result of DATA SUMMARY from bach-ui. 

### Describe the feature request

It is nice to be able to extract the result of DATA SUMMARY from bach-ui as a CSV files for more analysis or archiving purposes.

**Comment by hhlee445** [comment]
<img width="1582" alt="Screenshot 2024-04-10 at 3 52 27 PM" src="https://github.com/nasa/opera-sds-pcm/assets/47543396/2286c195-5536-4faf-8479-bdc5a21c30b2">

Add download or export button for CSV file

**Comment by hhlee445** [comment]
@chrisjrd Can we change  
1. the 3rd column (metadata) to filename and just list filename on the CSV file
2. filename to save include current time (ex. data_summary_20240410.csv)
