### ISSUE TITLE
[New Feature]: No rolling storage - localize DAAC S3 products directly to Verdi workers

### ISSUE THREAD

**Issue by riverma** [nasa/opera-sds-pcm#628]
### Checked for duplicates

Yes - I've already checked

### Alternatives considered

Yes - and alternatives don't suffice

### Related problems

Given that the source DAAC's that OPERA obtains products from are located in the same AWS region as OPERA, we could save in latency and storage costs if we did not copy S3 products from DAAC's storage over a rolling storage and then localized onto workers, and instead directly localized to workers as needed from DAAC S3.

### Describe the feature request

Current method:
```mermaid
graph LR
    A[DAAC S3 Storage] -->|Download products| B[OPERA S3 Rolling Storage]
    B -->|Localize products| C[OPERA Verdi Workers]
```

Proposed method:
```mermaid
graph TB
    A[DAAC S3 Storage] -->|Localize products| C[OPERA Verdi Workers]
```

**Comment by riverma** [comment]
Investigation needed:
- [ ] Can we localize sample ASF S3 data inside a private VPC Verdi worker @chrisjrd 
- [ ] Cost advantages @riverma

**Comment by hhlee445** [comment]
We can't copy a granule directly from ASF S3 to a private VPC verdi worker since we need to get a S3 credential which requires to use public VPC

**Comment by riverma** [comment]
> We can't copy a granule directly from ASF S3 to a private VPC verdi worker since we need to get a S3 credential which requires to use public VPC

Hi @hhlee445 - is it possible to get an S3 credential once (or renew) on a public VPC machine and share that cred with a private VPC verdi worker?
