### ISSUE TITLE
[New Feature]: Update the CMR audit files to account for the gdal dependency

### ISSUE THREAD

**Issue by hhlee445** [nasa/opera-sds-pcm#649]
### Checked for duplicates

Yes - I've already checked

### Alternatives considered

No - I haven't considered

### Describe the feature request

1. Update README as needed with note on native gdal install.
2. Update setup.py to install GDAL python package (NOT same thing as native gdal)

**Comment by chrisjrd** [comment]
the changes have been submitted to the develop branch directly.
See commits 
4ea8f298e845ceac019c616624c0d4ad68200a4c
and
e785689d26f634781189ed8779c24781296a24ff
