### ISSUE TITLE
Improve data subscriber logging

### ISSUE THREAD

**Issue by maseca** [nasa/opera-sds-pcm#67]
### Checked for duplicates

Yes - I've already checked

### Alternatives considered

Yes - and alternatives don't suffice

### Describe the feature request

https://github.com/nasa/opera-sds-pcm/pull/58#issuecomment-1081343444

> I noticed that most log message stored in _stderr.txt rather than _stdout.txt. The logging level was DEBUG, how can we change to lower logging level?

- [x] Change default logging level to INFO
- [x] Verify all relevant information is being logged on the INFO level
- [x] Capture summary of query and download from DAAC at the end of processing (# of files returned by query,# of successful download, # of failed download, # of skipped download, etc)

**Comment by hhlee445** [comment]
@maseca I don't see a logging message for summary of query and download from DAAC at the end of processing. Can you check again?
