### ISSUE TITLE
[Bug]:  RTC DEM file with extents  does not fully cover product geogrid with extents S/N

### ISSUE THREAD

**Issue by toandn-jpl** [nasa/opera-sds-pcm#683]
### Checked for duplicates

Yes - I've already checked

### Describe the bug

[StdErr] ValueError: ERROR the DEM file with extents S/N: [73.52874999999868,77.531249999999] W/E: [-95.46736111110435,-77.10819444443622], does not fully cover product geogrid with extents S/N: [73.48709048988043,77.44344706921333] W/E: [-94.52884705427306,-78.93660651711997]

SCIFLO_L2_RTC_S1__2.1.1-S1A_IW_SLC__1SDH_20231117T124336_20231117T124403_051257_062EF8_40AA-r1
[pge_20231118T035034.log](https://github.com/nasa/opera-sds-pcm/files/13479500/pge_20231118T035034.log)

[_stderr_triaged_job-SCIFLO_L2_RTC_S1__2.1.1-S1A_IW_SLC__1SDH_20231117T124336_20231117T124403_051257_062EF8_40AA-r1-20231118T034543.77847Z_task-8106c999-9147-4af3-b846-25366a4e51ba.txt](https://github.com/nasa/opera-sds-pcm/files/13479518/_stderr_triaged_job-SCIFLO_L2_RTC_S1__2.1.1-S1A_IW_SLC__1SDH_20231117T124336_20231117T124403_051257_062EF8_40AA-r1-20231118T034543.77847Z_task-8106c999-9147-4af3-b846-25366a4e51ba.txt)
### What did you expect?

I expected [...]

### Reproducible steps

```bash
Run 

SCIFLO_L2_RTC_S1__2.1.1-S1A_IW_SLC__1SDH_20231117T124336_20231117T124403_051257_062EF8_40AA-r1 
SCIFLO_L2_RTC_S1__2.1.1-S1A_IW_SLC__1SDH_20231119T122657_20231119T122727_051286_063007_87BB-r1
SCIFLO_L2_RTC_S1_STATIC__2.1.1-S1A_IW_SLC__1SDH_20231119T122657_20231119T122727_051286_063007_87BB-r1
...

...
```

### Environment

```bash
R2.1.0/R2.1.1

...
```

**Comment by collinss-jpl** [comment]
Granules reported have been retested using an ancillary margin of 200, which resolves the overlap error.
Ancillary margin set to 200km for RTC-S1 and RTC-S1-STATIC in release 2.2.0 in the following commit https://github.com/nasa/opera-sds-pcm/commit/71a0d84cca79fd3142ddcd0e6f558cc48b486201
