### ISSUE TITLE
[Bug]: DSWx_HLS Failed to download DSWx DEM file,  `/vsis3/opera-dem/EPSG4326/EPSG4326.vrt' does not exist in the file system

### ISSUE THREAD

**Issue by toandn-jpl** [nasa/opera-sds-pcm#685]
### Checked for duplicates

Yes - I've already checked

### Describe the bug

Exception Type: <class 'RuntimeError'>
Exception Value: Input precondition failure: Failed to download DSWx DEM file, reason: `/vsis3/opera-dem/EPSG4326/EPSG4326.vrt' does not exist in the file system, and is not recognized as a supported dataset name.
Traceback (most recent call last):
  File "/home/ops/verdi/ops/opera-pcm/opera_chimera/precondition_functions.py", line 940, in get_opera_ancillary
    staging_func(staging_func_args)
  File "/home/ops/verdi/ops/opera-pcm/tools/stage_dem.py", line 345, in main
    download_dem(polys, epsgs, dem_location, opts.outfile)
  File "/home/ops/verdi/ops/opera-pcm/tools/stage_dem.py", line 203, in download_dem
    translate_dem(vrt_filename, output_path, x_min, x_max, y_min, y_max)
  File "/home/ops/verdi/lib/python3.9/site-packages/backoff/_sync.py", line 105, in retry
    ret = target(*args, **kwargs)
  File "/home/ops/verdi/ops/opera-pcm/tools/stage_dem.py", line 138, in translate_dem
    ds = gdal.Open(vrt_filename, gdal.GA_ReadOnly)
  File "/opt/conda/lib/python3.9/site-packages/osgeo/gdal.py", line 4716, in Open
    return _gdal.Open(*args)
RuntimeError: `/vsis3/opera-dem/EPSG4326/EPSG4326.vrt' does not exist in the file system, and is not recognized as a supported dataset name.

[_stderr_triaged_job-SCIFLO_L3_DSWx_HLS__2.1.1-HLS.L30.T35SLA.2023317T085907.v2.0-r1-20231118T005003.323994Z_task-40abef76-a4ee-43d1-9da6-5b4d7d222bbf.txt](https://github.com/nasa/opera-sds-pcm/files/13479605/_stderr_triaged_job-SCIFLO_L3_DSWx_HLS__2.1.1-HLS.L30.T35SLA.2023317T085907.v2.0-r1-20231118T005003.323994Z_task-40abef76-a4ee-43d1-9da6-5b4d7d222bbf.txt)
### What did you expect?

I expected [...]

### Reproducible steps

```bash
Run:

job: SCIFLO_L3_DSWx_HLS__2.1.1-HLS.L30.T35SLA.2023317T085907.v2.0-r1-20231118T005003.323994Z
```

### Environment

```bash
- Version of this software [e.g. vX.Y.Z]
- Operating System: [e.g. MacOSX with Docker Desktop vX.Y]
...
```

**Comment by collinss-jpl** [comment]
Addressed in #687
