### ISSUE TITLE
[New Feature]: DSWx-S1 PGE Job Triggering Validator

### ISSUE THREAD

**Issue by riverma** [nasa/opera-sds-pcm#703]
### Checked for duplicates

Yes - I've already checked

### Alternatives considered

Yes - and alternatives don't suffice

### Related problems

The triggering logic for DSWx-S1 PGE is complex. We need an independent way to validate the triggering logic (i.e. submission of jobs) is working as prescribed by ADT. Further, steps towards an accounting tool (that can support #492) would be helpful.

### Describe the feature request

A script that validates DSWx-S1 triggering logic using a combination of NASA Earthdata CMR and the ADT provided MGRS Tile Database (which maps RTC bursts to tiles that need to be processed using triggering logic).

**Comment by riverma** [comment]
## Current Triggering Logic for DSWx-S1 PGE:

“X%” and “N hours” are PCM parameters that can be set.
- PCM queries for new RTC-S1 granules
- PCM checks for DSWx-S1 Tile Sets that are not yet processed
  - Any unprocessed Tile Sets with 100% of input RTC-S1 available are immediately submitted for processing
  - If an unprocessed Tile Set has >=X%, but <100%, PCM will start a timer lasting N hours.
    - If no new inputs are available after N hours, the Tile Set is processed with the data available
    - If new inputs become available in <N hours (but still <100% coverage), the timer resets.
  - If an unprocessed Tile Set has less than X% of inputs, no action is taken
- If new RTC-S1 products arrive for Tile Sets already processed (presumably they were processed with <100% of inputs), then PCM will _______.

## Expected Validator Logic for DSWx-S1 PGE:

The intention of the validation tool is to return _which tile sets should have been processed for a given set of RTC bursts and associated triggering logic / parameters_. The validation tool is highly dependent on _when_ the tool is run, as the list of available RTC bursts could change. 

- Input:
  - `T` time-range (start / end)
  - `X%` of RTC completion threshold for a given MGRS tile set
  - `N` hours for timer wait duration
- Steps:
  1. Query CMR for available RTC bursts matching `T`, denoted as `RTC Bursts`
  2. Take list of `RTC Bursts` and query MGRS Tile Database
     1. Query for `Tile Set IDs` that have 100% coverage for provided `RTC Bursts`
     2. Query for `Tile Set IDs` that have >= `X%` coverage for provided `RTC Bursts`
- Output:
  - List of `Tile Set IDs` that should have been processed
  - If the creation timestamps for RTC bursts have variance > `N` hours, return a warning that timer triggering logic should have been activated, and to ensure that the right number of tile set IDs processed matches the validator

**Comment by sjlewis-jpl** [comment]
I would like the script to be runnable/usable "offline", i.e. without CMR in the loop.  Having the ability to query CMR to generate the list of RTC products is a good feature, and something we definitely want.  I think just keeping Steps i and ii as separate functions, and use the output from Step i as part of the input to Step ii, and allowing Step ii to be invoked with some list (or text file, or whatever) would do the trick.  That would make this much more unit-testable as well.

**Comment by LucaCinquini** [comment]
Hi Rishi, very impressive, I tried it and it worked for me. A couple of comments on the installation:

o You also need to install python_cmr:
pip install python_cmr

o On my mac (Apple M2 pro chip) and Python 3.9.6 I could not install sqllite3 as from instructions, I had to build the wheel and install it in the virtual environment following the instructions here:
https://til.simonwillison.net/sqlite/build-specific-sqlite-pysqlite-macos

**Comment by riverma** [comment]
> Hi Rishi, very impressive, I tried it and it worked for me. A couple of comments on the installation:
> 
> o You also need to install python_cmr: pip install python_cmr
> 
> o On my mac (Apple M2 pro chip) and Python 3.9.6 I could not install sqllite3 as from instructions, I had to build the wheel and install it in the virtual environment following the instructions here: https://til.simonwillison.net/sqlite/build-specific-sqlite-pysqlite-macos

@LucaCinquini thank you for trying this out and your feedback! I've addressed your comments in the [latest commit](https://github.com/nasa/opera-sds-pcm/commit/90ce1493a27a618bf9714a906b4e3f6f31417635).

**Comment by sjlewis-jpl** [comment]
Hi Rishi - the functionality is all there.  I have some suggestions for refactors, and a few new (but not critical) features, below.  

- Make this importable & usable as a module
   - script portion inside an `if __name__ == '__main__'` block
   - change dashes to underscores in the filename
   - logic in the script portion limited to:  parse inputs, call the function.
- Make some unit tests, at least for the core logic (maybe we don't want our unit tests hitting the CMR servers?).
- Input:
   - Passing in just a list of Burst IDs (as an alternative to the list of RTC granule IDs) would be useful.
- Output:
   - Print a count of MGRS Tile IDs covered (useful when the list is long)
   - In each row of the table output, add additional columns with the number of input bursts seen, and the total number of input bursts expected ('Matching Burst Count' and 'Total Burst Count')
- Various other refactor suggestions - probably easier to handle through the PR interface.  I can also make some commits showing these suggestions.

**Comment by riverma** [comment]
### Summary of conversation with @chrisjrd regarding DSWx-S1 validation using validator script and existing code:
- General strategy for matching RTC batches from CMR to rows in the MGRS Tile DB is consistent with the coding strategy
- Validator script is using CMR Python API versus code using custom REST invocations to CMR
- `mgrs_tile_id` would uniquely identify DSWx-S1 jobs within a 12 day orbit cycle, but you need to add the acquisition orbit cycle number in order to uniquely identify mgrs tile ids / dswx-s1 jobs within the year time frame. Example: `MS_166_30$5`

### Next steps:
1. @riverma  to add handling the 12-day orbit cycle issue, by adding acquisition cycle ID.
   - Value of `0` means Jan 1st - Jan 12th, value of `1` means Jan 12th - Jan 24th
   - See code to generate this number [here](https://github.com/nasa/opera-sds-pcm/blob/5a35be7b79dc5dbbed0f2544087ff3870840e3f4/data_subscriber/rtc/rtc_query.py#L207-L225). 
2. Be ready to perform a test using the below metadata mappings in OPERA SDS

### Metadata matching in OPERA SDS Elasticsearch:

- DSWx-S1 Product Index (GRQ): `rtc_catalog-YYYY-MM`
- - Metadata: need to confirm with @collinss-jpl 
- DSWx-S1 Job Index (Mozart): `job_statuses-YYYY-MM`
- - Metadata: https://github.com/nasa/opera-sds-pcm/blob/5a35be7b79dc5dbbed0f2544087ff3870840e3f4/data_subscriber/rtc/rtc_job_submitter.py#L38-L54

**Comment by sjlewis-jpl** [comment]
Another feature that would be useful is the ability to output the MGRS Tile IDs that were produced, not just the Tile Set IDs.  Maybe as an optional output?  Or as another column in the output table?  That information would make it easier to compare the script's output against the results of testing (or operations), where we only see the Tile IDs in the output granule name.

**Comment by riverma** [comment]
## Test Cases

### 100% coverage case

Command:
`python dswx-s1-validator.py --start "2023-12-05T00:00:00Z" --end "2023-12-05T00:59:59Z" --db MGRS_tile_collection_v0.2.sqlite --threshold 100`

Expected Tile Sets:
```
+-------------+---------------------+
| MGRS Set ID | Coverage Percentage |
+-------------+---------------------+
|  MS_165_13  |        100.0        |
|  MS_165_14  |        100.0        |
|  MS_165_15  |        100.0        |
|  MS_165_16  |        100.0        |
|  MS_165_17  |        100.0        |
|  MS_165_18  |        100.0        |
|  MS_165_19  |        100.0        |
|  MS_165_20  |        100.0        |
|  MS_165_21  |        100.0        |
|  MS_165_22  |        100.0        |
|  MS_165_23  |        100.0        |
|  MS_165_24  |        100.0        |
|  MS_165_25  |        100.0        |
|  MS_165_26  |        100.0        |
|  MS_165_27  |        100.0        |
|  MS_165_73  |        100.0        |
|  MS_165_74  |        100.0        |
|  MS_165_75  |        100.0        |
|  MS_165_76  |        100.0        |
|  MS_165_77  |        100.0        |
|  MS_165_78  |        100.0        |
|  MS_165_79  |        100.0        |
|  MS_165_80  |        100.0        |
|  MS_165_81  |        100.0        |
|  MS_165_82  |        100.0        |
|  MS_165_83  |        100.0        |
|  MS_165_84  |        100.0        |
|  MS_165_85  |        100.0        |
|  MS_165_86  |        100.0        |
|  MS_165_87  |        100.0        |
|  MS_165_88  |        100.0        |
|  MS_165_89  |        100.0        |
+-------------+---------------------+
```

### 50% coverage

Command:
`python dswx-s1-validator.py --start "2023-12-05T00:00:00Z" --end "2023-12-05T00:59:59Z" --db MGRS_tile_collection_v0.2.sqlite --threshold 50`

Expected Tile Sets:
```
+-------------+---------------------+
| MGRS Set ID | Coverage Percentage |
+-------------+---------------------+
|  MS_165_12  |        85.0         |
|  MS_165_13  |        100.0        |
|  MS_165_14  |        100.0        |
|  MS_165_15  |        100.0        |
|  MS_165_16  |        100.0        |
|  MS_165_17  |        100.0        |
|  MS_165_18  |        100.0        |
|  MS_165_19  |        100.0        |
|  MS_165_20  |        100.0        |
|  MS_165_21  |        100.0        |
|  MS_165_22  |        100.0        |
|  MS_165_23  |        100.0        |
|  MS_165_24  |        100.0        |
|  MS_165_25  |        100.0        |
|  MS_165_26  |        100.0        |
|  MS_165_27  |        100.0        |
|  MS_165_72  |        60.0         |
|  MS_165_73  |        100.0        |
|  MS_165_74  |        100.0        |
|  MS_165_75  |        100.0        |
|  MS_165_76  |        100.0        |
|  MS_165_77  |        100.0        |
|  MS_165_78  |        100.0        |
|  MS_165_79  |        100.0        |
|  MS_165_80  |        100.0        |
|  MS_165_81  |        100.0        |
|  MS_165_82  |        100.0        |
|  MS_165_83  |        100.0        |
|  MS_165_84  |        100.0        |
|  MS_165_85  |        100.0        |
|  MS_165_86  |        100.0        |
|  MS_165_87  |        100.0        |
|  MS_165_88  |        100.0        |
|  MS_165_89  |        100.0        |
|  MS_165_90  |        60.98        |
+-------------+---------------------+
```


### Midnight Intersecting Time Range w/ 50% Coverage

Command:
`python dswx-s1-validator.py --start "2023-12-04T23:30:00Z" --end "2023-12-05T00:30:00Z" --db MGRS_tile_collection_v0.2.sqlite --threshold 50`

Expected Tile Sets:
```
+-------------+---------------------+
| MGRS Set ID | Coverage Percentage |
+-------------+---------------------+
| MS_164_153  |        72.09        |
| MS_164_154  |        100.0        |
| MS_164_155  |        100.0        |
| MS_164_156  |        100.0        |
| MS_164_157  |        100.0        |
| MS_164_158  |        100.0        |
| MS_164_159  |        100.0        |
| MS_164_160  |        54.76        |
|  MS_165_6   |        100.0        |
|  MS_165_7   |        100.0        |
|  MS_165_8   |        100.0        |
|  MS_165_9   |        100.0        |
|  MS_165_10  |        100.0        |
|  MS_165_11  |        100.0        |
|  MS_165_12  |        100.0        |
|  MS_165_13  |        100.0        |
|  MS_165_14  |        100.0        |
|  MS_165_15  |        100.0        |
|  MS_165_16  |        100.0        |
|  MS_165_17  |        100.0        |
|  MS_165_18  |        100.0        |
|  MS_165_19  |        100.0        |
|  MS_165_20  |        100.0        |
|  MS_165_21  |        100.0        |
|  MS_165_22  |        100.0        |
|  MS_165_23  |        100.0        |
|  MS_165_24  |        100.0        |
|  MS_165_25  |        100.0        |
|  MS_165_26  |        100.0        |
|  MS_165_27  |        100.0        |
+-------------+---------------------+
```

**Comment by sjlewis-jpl** [comment]
I believe the `--threshold` parameter just filters the output by the Coverage Percentage, yes?  I think it would be more useful to have the tests use `--threshold 1` to show ALL of the TileSets touched by the time range.

Well, we should have one test with a higher threshold, just to prove that the filtering works correctly.

**Comment by riverma** [comment]
> I believe the `--threshold` parameter just filters the output by the Coverage Percentage, yes? 

@sjlewis-jpl - you're correct, the `--threshold` parameter is really just for display purposes. A Pandas DataFrame is filtered before showing the results based on the threshold value. See snippet [here](https://github.com/nasa/opera-sds-pcm/blob/issue-703/report/dswx-s1-validator/dswx_s1_validator.py#L261-L264).

> I think it would be more useful to have the tests use --threshold 1 to show ALL of the TileSets touched by the time range.

Hmm. Certainly that's a good test case to add (will do). However, we will want to also test the functionality of the threshold parameter having "in-between" values between 1 and 100. I just added a test case about for the threshold value of 1.

**Comment by riverma** [comment]
## Edge Cases

Thanks to @jungkyoJung for these!

### Only one burst are available

Command:
`python dswx_s1_validator.py --start "2023-11-01T01:28:15Z" --end "2023-11-01T01:34:15Z" --db MGRS_tile_collection_v0.2.sqlite --threshold 1`

Expected Tile Sets:
```
```


### Four polarizations are available: VV/VH/HH/HV

Command:
`python dswx_s1_validator.py --start "2023-11-01T22:49:51Z" --end "2023-11-01T22:55:51Z" --db MGRS_tile_collection_v0.2.sqlite --threshold 1`

Expected Tile Sets:
```
```


### HH/ HV polarizations are available

Command:
`python dswx_s1_validator.py --start "2023-11-08T22:41:33Z" --end "2023-11-08T22:47:33Z" --db MGRS_tile_collection_v0.2.sqlite --threshold 1`

Expected Tile Sets:
```
```


### Small portion of land compared to water region

Command:
`python dswx_s1_validator.py --start "2023-11-11T22:57:27Z" --end "2023-11-11T23:03:27Z" --db MGRS_tile_collection_v0.2.sqlite --threshold 1`

Expected Tile Sets:
```
```


### Only water covered.

Command:
`python dswx_s1_validator.py --start "2023-11-11T23:00:48Z" --end "2023-11-11T23:06:48Z" --db MGRS_tile_collection_v0.2.sqlite --threshold 1`

Expected Tile Sets:
```
```


### only water covered. Ancillary data may have only invalid values

Command:
`python dswx_s1_validator.py --start "2023-11-01T22:43:18Z" --end "2023-11-01T22:49:18Z" --db MGRS_tile_collection_v0.2.sqlite --threshold 1`

Expected Tile Sets:
```
```

### 56 bursts are required

Command:
`python dswx_s1_validator.py --start "2023-10-23T18:27:51Z" --end "2023-10-23T18:33:51Z" --db MGRS_tile_collection_v0.2.sqlite --threshold 1`

Expected Tile Sets:
```
```


### Anti-meridian

Command:
`python dswx_s1_validator.py --start "2023-11-11T18:29:17Z" --end "2023-11-11T18:35:17Z" --db MGRS_tile_collection_v0.2.sqlite --threshold 1`

Expected Tile Sets:
```
```


### Memory issue and possible missing ancillary data when 100 % coverage required but only 61 available

Command:
`python dswx_s1_validator.py --start "2023-11-01T11:32:48Z" --end "2023-11-01T11:38:48Z" --db MGRS_tile_collection_v0.2.sqlite --threshold 1`

Expected Tile Sets:
```
```

**Comment by philipjyoon** [comment]
In order to test the following requirement:
"If an unprocessed Tile Set has >=X%, but <100%, PCM will start a timer lasting N hours. If no new inputs are available after N hours, the Tile Set is processed with the data available"

Multiple series of hourly queries/triggering need to be run contiguously. e.g.:
1. Run from 00:00:00 to 01:00:00. Some will meet 100% and trigger; some will stay round
2. Run from 01:00:00 to 02:00:00. Some of the left over from the last hour may add up with this new set of data, meet the % threshold, and then trigger. (If the grace period is 60 mins that is)
 
That's the only way to have any unprocessed Tile Set to be processed. I think this test case is missing here.

**Comment by riverma** [comment]
@philipjyoon - thanks for your insight.

If enough time has passed, we would expect the results of the validator script at `>= X%` threshold coverage to match PCM product generation. It's trickier close to FWD processing, but running the simple coverage check after a few days should suffice for your use case. Let me know if you think otherwise.

**Comment by philipjyoon** [comment]
@riverma The following two use-cases can (and will over time) yield different trigger logic output:

1. Query for one hour every time iteratively over 5 hrs and then process triggering rule at every hour using the prior state of the system, taking into account the time at which each granule entered the system (when they were queried).
2. Query once to cover all 5 hrs and process triggering rules over the entire set at once without factoring in the time at which the granules entered the system.

They would produce different results because the time at which the granules entered the system is one of the factors in the triggering rule. Slide 5 here illustrate this: https://docs.google.com/presentation/d/1maA2nqimOXFzMfGfIF0JcTd2XvB0fh3gjtwuya93CnI/edit?pli=1#slide=id.g28b86c493b7_0_0

It seems the test cases listed here and the way the validator works currently are performing #2 only. I think it's crucial to test for the use-case in that design diagram, sooner the better and preferably during development as opposed to I&T.

**Comment by riverma** [comment]
Hi @philipjyoon - thanks for your comments. I'm still not getting the difference though, from the perspective of the validator script. Let's try and work through the below visual example to see if and how we differ in interpretation. 

**Assume:**
- 60% burst coverage is needed for any given MGRS Tile Set to be kicked off for DSWx-S1 processing
- FWD processing rules indicate triggering rules are evaluated every hour, and reprocessing occurs if more bursts are available past the 60% mark but still less than 100% up to a maximum amount of wait time (say 10 hours)

**Summary of the below processing scenario:**
- DSWx-S1 job is triggered 3 times for MGRS Tile Set ID `MS_166_30`
- 100% of the bursts for `MS_166_30` are expected to be covered within the final DSWx-S1 product (i.e. v3 at time window 10)

**My understanding / conclusion:**
1. The validator script _doesn't and shouldn't_ care how many times processing kicked off (that's an internal PCM detail)
2. The validator script _should care about the existence and composition of DSWx-S1 products_ by verifying:
    - `MS_166_30` is processed as part of a DSWx-S1 job
    - `MS_166_30` DSWx-S1 product contains 100% burst coverage and no less
3. Your two scenarios described (iterative vs all-at-once) lead to the same effective outcome when evaluated at time step 10
4. The examples I've provided earlier in this ticket don't spell out the specific burst IDs that should have been evaluated. Doing so will ensure we verify the "composition" of the DSWx-S1 products not just the existence - i.e. we'll have covered the (re-)triggering scenarios you described. 


# Time Window 1

| MS_166_30 (20% coverage)            | ... |
|-------------------------------------|---|
| t020_041121_iw1 ✅                  | ... |
| t020_041122_iw2 ✅                  | ... |
| t020_041123_iw3 ❌                   | ... |
| t020_041124_iw4 ❌                  | ... |
| t020_041125_iw5 ❌                   | ... |
| t020_041126_iw6 ❌                   | ... |
| t020_041127_iw7 ❌                   | ... |
| t020_041128_iw8 ❌                  | ... |
| t020_041129_iw9 ❌                  | ... |
| t020_041130_iw10 ❌                 | ... |

**Notes:**
- No processing triggered

# Time Window 4

| MS_166_30 (40% coverage)            | ... |
|-------------------------------------|---|
| t020_041121_iw1 ✅                  | ... |
| t020_041122_iw2 ✅                  | ... |
| t020_041123_iw3 ✅                  | ... |
| t020_041124_iw4 ✅                  | ... |
| t020_041125_iw5 ❌                  | ... |
| t020_041126_iw6 ❌                | ... |
| t020_041127_iw7 ❌                   | ... |
| t020_041128_iw8 ❌                  | ... |
| t020_041129_iw9 ❌                  | ... |
| t020_041130_iw10 ❌                 | ... |

**Notes:**
- No processing triggered

# Time Window 5

| MS_166_30 (60% coverage)            | ... |
|-------------------------------------|---|
| t020_041121_iw1 ✅                  | ... |
| t020_041122_iw2 ✅                  | ... |
| t020_041123_iw3 ✅                   | ... |
| t020_041124_iw4 ✅                  | ... |
| t020_041125_iw5 ✅                   | ... |
| t020_041126_iw6 ✅                   | ... |
| t020_041127_iw7 ❌                   | ... |
| t020_041128_iw8 ❌                  | ... |
| t020_041129_iw9 ❌                  | ... |
| t020_041130_iw10 ❌                 | ... |

**Notes:**
- 60% threshold for coverage reached
- No processing triggered because we always wait two more time window intervals just in case more data is coming

# Time Window 7

| MS_166_30 (60% coverage)            | ... |
|-------------------------------------|---|
| t020_041121_iw1 ✅                  | ... |
| t020_041122_iw2 ✅                  | ... |
| t020_041123_iw3 ✅                   | ... |
| t020_041124_iw4 ✅                  | ... |
| t020_041125_iw5 ✅                   | ... |
| t020_041126_iw6 ✅                   | ... |
| t020_041127_iw7 ❌                   | ... |
| t020_041128_iw8 ❌                  | ... |
| t020_041129_iw9 ❌                  | ... |
| t020_041130_iw10 ❌                 | ... |

**Notes:**
- No new bursts available
- DSWx-S1 PGE triggered

# Time Window 8

| MS_166_30 (60% coverage)            | ... |
|-------------------------------------|---|
| t020_041121_iw1 ✅                  | ... |
| t020_041122_iw2 ✅                  | ... |
| t020_041123_iw3 ✅                   | ... |
| t020_041124_iw4 ✅                  | ... |
| t020_041125_iw5 ✅                   | ... |
| t020_041126_iw6 ✅                   | ... |
| t020_041127_iw7 ❌                   | ... |
| t020_041128_iw8 ❌                  | ... |
| t020_041129_iw9 ❌                  | ... |
| t020_041130_iw10 ❌                 | ... |

**Notes:**
- No new bursts available
- No processing triggered

# Time Window 9

| MS_166_30 (80% coverage)            | ... |
|-------------------------------------|---|
| t020_041121_iw1 ✅                  | ... |
| t020_041122_iw2 ✅                  | ... |
| t020_041123_iw3 ✅                   | ... |
| t020_041124_iw4 ✅                  | ... |
| t020_041125_iw5 ✅                   | ... |
| t020_041126_iw6 ✅                   | ... |
| t020_041127_iw7 ✅                   | ... |
| t020_041128_iw8 ✅                  | ... |
| t020_041129_iw9 ❌                  | ... |
| t020_041130_iw10 ❌                 | ... |

**Notes:**
- 2 new bursts available
- DSWx-S1 PGE (re-)triggered

# Time Window 10

| MS_166_30 (100% coverage)            | ... |
|-------------------------------------|---|
| t020_041121_iw1 ✅                  | ... |
| t020_041122_iw2 ✅                  | ... |
| t020_041123_iw3 ✅                   | ... |
| t020_041124_iw4 ✅                  | ... |
| t020_041125_iw5 ✅                   | ... |
| t020_041126_iw6 ✅                   | ... |
| t020_041127_iw7 ✅                   | ... |
| t020_041128_iw8 ✅                  | ... |
| t020_041129_iw9 ✅                  | ... |
| t020_041130_iw10 ✅                 | ... |

**Notes:**
- 2 new bursts available
- DSWx-S1 PGE (re-)triggered

**Comment by riverma** [comment]
Update: @philipjyoon and I discussed the above and came to the following conclusion: if the validator script is run after enough time post FWD processing, it will sufficiently cover the testing scenarios @philipjyoon brought up.
