### ISSUE TITLE
[New Feature]: filter SLC products with SV_* attributes

### ISSUE THREAD

**Issue by chrisjrd** [nasa/opera-sds-pcm#731]
### Checked for duplicates

Yes - I've already checked

### Alternatives considered

Yes - and alternatives don't suffice

### Related problems

I'm frustrated when [...] happens as documented in issue-XYZ

### Describe the feature request

We need to skip processing SLC products without `SV_{POSITION,VELOCITY}_{PRE,POST}` attributes

**Comment by hhlee445** [comment]
This solution won't work if the metadata update occurred after the product generation latency. Will use another method.
