### ISSUE TITLE
[New Feature]: DSWx-HLS Upstream Data Updates

### ISSUE THREAD

**Issue by riverma** [nasa/opera-sds-pcm#747]
### Checked for duplicates

Yes - I've already checked

### Alternatives considered

Yes - and alternatives don't suffice

### Related problems

N/A

### Describe the feature request

We need to account for upcoming DSWx-HLS changes that have updated the upstream algorithm. The data changes apparently do not required PGE updates.

The PCM changes needed for this are:
- No updates to the input data stream from LP.DAAC
- Updates to the collection information for DSWX-HLS as we push data to PO.DAAC. Basically, modify `settings.yml` 

We should have a branch ready for release with the above changes that can be deployed to our OPS venue.

**Comment by hhlee445** [comment]
Need to modify collection name for DSWx-HLS product type

**Comment by hhlee445** [comment]
Collection name was modified in setttings.yaml
