### ISSUE TITLE
[New Feature]: Add tag to  PGE ASG launch template

### ISSUE THREAD

**Issue by hhlee445** [nasa/opera-sds-pcm#748]
### Checked for duplicates

Yes - I've already checked

### Alternatives considered

No - I haven't considered

### Describe the feature request

Project wants to add tag EC2 instances according to the PGE to evaluate the AWS costs separately. 
Each PGE has its own ASG fleet so we want to tag per PGE ASG.

**Comment by philipjyoon** [comment]
It turns out we are already doing this. No further action necessary

<img width="1070" alt="image" src="https://github.com/nasa/opera-sds-pcm/assets/104090313/9a788e41-6778-460f-81b8-8cfba03b0fcc">
