### ISSUE TITLE
[Task]: Reduce the frequency of ES backups to 1/day from hourly

### ISSUE THREAD

**Issue by hhlee445** [nasa/opera-sds-pcm#757]
### Checked for similar tasks

Yes - I've already checked

### Describe the task

The task is to reduce the frequency of ES backups to 1/day from hourly. Hourly backup was creating too many snapshots data.

**Comment by philipjyoon** [comment]
Performed method 1

66c57a603ceb61bae76f16dd34b87e5d2cd02945
https://github.com/nasa/opera-sds-pcm/tree/757_daily_es_snapshots
