### ISSUE TITLE
terraform feature: Create a text file on Mozart upon deployment that contains PCM release version information

### ISSUE THREAD

**Issue by philipjyoon** [nasa/opera-sds-pcm#764]
### Checked for duplicates

Yes - I've already checked

### Alternatives considered

Yes - and alternatives don't suffice

### Related problems

I'm frustrated when it's basically impossible to figure out which PCM version a particular deployment is running. We have to manually track this and it's prone to user-error.

### Describe the feature request

Create a terraform resource that creates a text file in the home directory of hysdsops user on Mozart machine that includes information such as following:

- Deployment date/time
- OPERA PCM release version
- Each PGE version (these are diff from the PCM version)

**Comment by hhlee445** [comment]
'sds pkg ls' for the PCM version  
'docker image ls'  for the PGE versions

**Comment by philipjyoon** [comment]
What @hhlee445 mentioned meets the need.
