### ISSUE TITLE
[Bug]: dswx-s1 native-id flow ignores low coverage target override

### ISSUE THREAD

**Issue by chrisjrd** [nasa/opera-sds-pcm#780]
### Checked for duplicates

Yes - I've already checked

### Describe the bug

native-id flow is using grace period logic and not respecting coverage target override

### What did you expect?

grace period logic should be skipped and coverage target should be respected

### Reproducible steps

```bash
python3 ~/mozart/ops/opera-pcm/data_subscriber/daac_data_subscriber.py query -c OPERA_L2_RTC-S1_V1   --job-queue=opera-job_worker-rtc_data_download --chunk-size 1 --release-version=773_flexible_s3_creds --native-id=OPERA_L2_RTC-S1_T069-146305-IW3_20210927T100632Z_20240320T213757Z_S1A_30_v1.0 --endpoint=UAT --coverage-target=1
```

### Environment

```bash
- tested in local dev environment
```

**Comment by hhlee445** [comment]
Duplicate issue https://github.com/nasa/opera-sds-pcm/issues/788
