### ISSUE TITLE
[New Feature]: support a configurable minimum number of RTC bursts for DSWx-S1 workflow

### ISSUE THREAD

**Issue by chrisjrd** [nasa/opera-sds-pcm#828]
### Checked for duplicates

Yes - I've already checked

### Alternatives considered

Yes - and alternatives don't suffice

### Describe the feature request

I need or want OPERA SDS PCM to run DSWx-S1 sciflo if there are at least N bursts available per RTC burst set. Where N = 4

**Comment by hhlee445** [comment]
Delivered in https://github.com/nasa/opera-sds-pcm/pull/838
