### ISSUE TITLE
[Bug]: SLC ProductionDateTime is not consistently accurate enough for reporting purposes

### ISSUE THREAD

**Issue by chrisjrd** [nasa/opera-sds-pcm#829]
### Checked for duplicates

Yes - I've already checked

### Describe the bug

Generating accountability reports show that retrieval time for SLC products is inaccurate. This inaccuracy comes from the metadata in CMR. We should use ProviderDates Insert timestamps for reporting purposes for SLC and other products.

### What did you expect?

I expected retrieval time for SLC to be some time after sensor time.

### Reproducible steps

```bash
1.ingest SLC
2. generate a retrieval time report in bach-ui
3. observe retrieval times and public available date times.
```

### Environment

```bash
- INT
```

**Comment by hhlee445** [comment]
Store both ProviderDate: Insert and productionDateTime.
