### ISSUE TITLE
[New Feature]: Launch multiple workers by data download timer

### ISSUE THREAD

**Issue by hhlee445** [nasa/opera-sds-pcm#85]
### Checked for duplicates

Yes - I've already checked

### Alternatives considered

Yes - and alternatives don't suffice

### Describe the feature request

Current DAAC data download timer submits a job using only one worker to download data from DAAC to our ISL bucket. We need to be able to launch many workers to download data simultaneously.

**Comment by riverma** [comment]
@chrisjrd - we should be able to control the level of parallelization for how many download workers to launch. Any thoughts on how to support that?
