### ISSUE TITLE
[Task]: Implement ECMWF file usage in DISP-S1 Workflow

### ISSUE THREAD

**Issue by collinss-jpl** [nasa/opera-sds-pcm#967]
### Checked for similar tasks

Yes - I've already checked

### Describe the task

Ticket to implement inclusion of ECMWF files when staging products for use with a DISP-S1 job.

This feature should include a toggle (in settings.yaml) to bypass inclusion of ECMWF files for ease of testing while we are waiting for files to be populated in S3.

The staging logic should also query S3 to ensure existence of the expected files (based on acquisition dates of input CSLC products) before they are included with the RunConfig for the job.

### Prerequisites or Requirements

```bash
1.
2.
3.
...
```

### Expected Deliverables

```bash
1.
2.
3.
...
```

**Comment by hhlee445** [comment]
Tropospheric Correction PGE will process the ECMWF data. DISP-S1 won't need to use the ECMWF data.
