### ISSUE TITLE
[Bug]: data_subscriber_download_timer throws exception when there is no data to download

### ISSUE THREAD

**Issue by hhlee445** [nasa/opera-sds-pcm#99]
### Checked for duplicates

Yes - I've already checked

### Describe the bug

When I did testing hlsl30_query_timer, hlss30_query_timer and data_subscriber_download_timer, I noticed that data_subscriber_download throws exception as below when hlsl30_query_timer and hlss30_query_timer failed to execute. 

Traceback (most recent call last):
File "/home/ops/verdi/ops/hysds-1.1.5/hysds/job_worker.py", line 1237, in run_job
raise RuntimeError("Got non-zero exit code: {}".format(status))
RuntimeError: Got non-zero exit code: 1

### What did you expect?

I expected the data_subscriber_download_timer to execute without any error and reported out that there is no data_subscriber_catalog ES index exists or no data to download.

### Environment

```bash
- PCM branch: issue_75 
- Lambda branch: issue_75
```

**Comment by maseca** [comment]
Could you please link me to the script output? Is the issue_75 PR dependent on this fix?

**Comment by hhlee445** [comment]
http://opera-dev-triage-fwd-hyunlee.s3-website-us-west-2.amazonaws.com/triaged_job-data-subscriber-download-timer-20220512T172700_20220512T173700-20220512T173722.390749Z_task-648de534-1a1a-4b6f-9a8c-d922b2ebbbef
